<?php if (!empty($this->updateOutput)): ?>
    <p><?php echo $this->escapeHtml($this->translate('Result:')); ?></p>
    <?php foreach ($this->updateOutput as $message): ?>
        <p><?php echo nl2br($this->escapeHtml($message)); ?></p>
    <?php endforeach; ?>
<?php else: ?>
    <?php if ($this->isLatest): ?>
        <p><?php echo $this->escapeHtml($this->translate('You already have the latest version')); ?></p>
    <?php else: ?>
        <p><?php echo $this->escapeHtml(sprintf($this->translate('Version %s has been released, please upgrade for security issues.'), $this->latestVersion)); ?>
        <br><?php echo $this->translate('You can follow this project on github:'); ?> <a href="https://github.com/GotCms/GotCms" target="_blank">https://github.com/GotCms/GotCms</a></p>

        <?php if (!empty($this->datatypesErrors)): ?>
            <div class="datatypes-errors">
                <p><?php echo $this->escapeHtml($this->translate('These datatypes may have problems:')); ?></p>
                <ul>
                    <?php foreach ($this->datatypesErrors as $error): ?>
                        <li><?php echo $this->escapeHtml($error); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if (!empty($this->modulesErrors)): ?>
            <div class="modules-errors">
                <p><?php echo $this->escapeHtml($this->translate('These modules may have problems:')); ?></p>
                <ul>
                    <?php foreach ($this->modulesErrors as $error): ?>
                        <li><?php echo $this->escapeHtml($error); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if (empty($this->gitProject)): ?>
            <p><?php echo $this->escapeHtml($this->translate("Yout can't update this project because you don't clone it with git")); ?></p>
        <?php else: ?>
            <form action="<?php echo $this->url(); ?>" method="post" id="update-form">
                <ul>
                    <li>
                        <label>
                            <input type="radio" name="adapter" value="git">Git
                        </label>
                    </li>
                </ul>

                <div>
                    <input id="input-save" class="btn btn-warning" type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Update')); ?>">
                </div>
            </form>
            <script type="text/javascript">
                Gc.initUpdate('<?php echo $this->escapeJs($this->translate('Do you really want to update GotCms?')); ?>');
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

