<h2>..:: <?php echo $this->escape($this->translate('Managing Views')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url(array(), 'viewAdd'); ?>" title=""><?php echo $this->escape($this->translate('Add')); ?></a></li>
    <li><a href="<?php echo $this->url(array(), 'viewList'); ?>" title=""><?php echo $this->escape($this->translate('List')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translate('Managing Layouts')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url(array(), 'layoutAdd'); ?>" title=""><?php echo $this->escape($this->translate('Add')); ?></a></li>
    <li><a href="<?php echo $this->url(array(), 'layoutList'); ?>" title=""><?php echo $this->escape($this->translate('List')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translate('Managing Datatypes')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url(array(), 'datatypeAdd'); ?>" title=""><?php echo $this->escape($this->translate('Add')); ?></a></li>
    <li><a href="<?php echo $this->url(array(), 'datatypeList'); ?>" title=""><?php echo $this->escape($this->translate('List')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translate('Managing Document types')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url(array(), 'documentTypeAdd'); ?>" title=""><?php echo $this->escape($this->translate('Add')); ?></a></li>
    <li><a href="<?php echo $this->url(array(), 'documentTypeList'); ?>" title=""><?php echo $this->escape($this->translate('List')); ?></a></li>
</ul>
