<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <title><?php echo $this->escapeHtml($this->translate('Installation')); ?> - GotCms</title>

  <meta name="viewport" content="width=device-width">
    <?php
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript()
        ->appendFile($this->cdnBackend('/backend/js/libs/modernizr-2.6.2.min.js'), 'text/javascript')
        ->appendFile($this->cdnBackend('/backend/js/libs/jquery-1.10.2.min.js'), 'text/javascript')
        ->appendFile($this->cdnBackend('/backend/js/plugins.js'), 'text/javascript')
        ->appendFile($this->cdnBackend('/backend/js/generic-classes.js'), 'text/javascript')
        ->appendFile($this->cdnBackend('/backend/js/gotcms.js'), 'text/javascript');

    echo $this->HeadLink()
        ->appendStylesheet($this->cdnBackend('/backend/css/style.css'))
        ->appendStylesheet($this->cdnBackend('/backend/css/install.css'));
    ?>
</head>
<body>
    <header class="gradient-black">
        <div id="logo">&nbsp;</div>
        <h1><?php echo $this->escapeHtml($this->translate('Installation')); ?></h1>
    </header>
    <div id="main-installer">
        <div class="content">
        <nav>
                <?php echo $this->partial('application/install/steps.phtml', array('currentRoute' => $this->currentRoute)); ?>
            </nav>
            <section>
                <?php echo $this->partial('messages.phtml', array('messages' => $this->flashMessages)); ?>
                <?php if (!empty($this->currentRoute)): ?>
                    <form action="<?php echo $this->url($this->currentRoute); ?>" method="post">
                <?php endif; ?>

                <?php echo $this->content; ?>

                <?php if (!empty($this->currentRoute)): ?>
                        <div class="button-submit">
                            <input class="button" type="submit" value="<?php echo $this->escapeHtml($this->translate('Continue')); ?>">
                        </div>
                    </form>
                <?php endif; ?>
            </section>

            <div style="clear:both;"></div>
        </div>
    </div>

    <footer>
        © <?php echo $this->escapeHtml(date('Y')); ?> <a href="http://www.got-cms.com">GotCms <?php echo $this->version; ?></a>
    </footer>
</body>
</html>
