<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <title><?php echo $this->escapeHtml($this->translate('Admin panel')); ?> - GotCms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300" />

    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>

    <?php if (!$this->debugIsActive): ?>
        <?php $this->headScript()->prependFile($this->cdnBackend('/backend/js/gotcms.min.js'), 'text/javascript'); ?>
        <?php $this->headLink()->prependStylesheet($this->cdnBackend('/backend/css/gotcms-install.min.css')); ?>
    <?php else: ?>
        <?php
        $this->headScript()
            ->prependFile($this->cdnBackend('/backend/js/gotcms.js'), 'text/javascript')
            ->prependFile($this->cdnBackend('/backend/js/generic-classes.js'), 'text/javascript')
            ->prependFile($this->cdnBackend('/backend/js/vendor/jquery-ui-1.10.3.custom.min.js'), 'text/javascript')
            ->prependFile($this->cdnBackend('/backend/js/vendor/jquery.browser.js'), 'text/javascript')
            ->prependFile($this->cdnBackend('/backend/js/bootstrap.min.js'), 'text/javascript')
            ->prependFile($this->cdnBackend('/backend/js/vendor/jquery-1.10.2.min.js'), 'text/javascript');
        ?>
        <link rel="stylesheet" type="text/less" href="<?php echo $this->cdnBackend('/backend/css/gotcms-install.less'); ?>" />
        <script type="text/javascript">
             var less = less || {};
             less.env = "development";
        </script>
        <script src="<?php echo $this->cdnBackend('/backend/js/vendor/less-1.5.0.min.js'); ?>"></script>
    <?php endif; ?>

    <?php echo $this->headScript(); ?>
    <?php echo $this->HeadLink(); ?>

    <?php $module = empty($this->routeParams['module']) ? null : strtolower($this->routeParams['module']); ?>
</head>
<body class="install">
    <header class="navbar navbar-default navbar-fixed-top" id="navbar">
        <?php echo $this->partial('navigation.phtml', array('active' => $module)); ?>
    </header>

    <div class="main-container container">
        <div id="sidebar" class="sidebar sidebar-fixed col-lg-2">
            <?php echo $this->partial('application/install/steps.phtml', array('currentRoute' => $this->currentRoute)); ?>
        </div>
        <div class="col-lg-12 main-content">
            <?php echo $this->partial('messages.phtml', array('messages' => $this->flashMessages)); ?>
            <?php if (empty($this->currentRoute)): ?>
                <div class="page-content">
                    <?php echo $this->content; ?>
                </div>
            <?php else: ?>
                <form action="<?php echo $this->url($this->currentRoute); ?>" method="post">
                    <div class="page-content">
                        <?php echo $this->content; ?>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-warning" type="submit" value="<?php echo $this->escapeHtml($this->translate('Continue')); ?>">
                    </div>
                </form>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
