<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <title><?php echo $this->escapeHtml($this->translate('Admin panel')); ?> - GotCms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" />

    <?php
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    $this->headScript()
        ->prependFile($this->cdnBackend('/backend/js/gotcms.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/generic-classes.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/jquery.contextMenu.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/jquery.jstree.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/codemirror/mode/php/php.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/codemirror/mode/clike/clike.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/codemirror/mode/css/css.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/codemirror/mode/javascript/javascript.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/codemirror/mode/xml/xml.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/codemirror/lib/codemirror.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/jquery-ui-1.10.3.custom.min.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/jquery.browser.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/bootstrap.min.js'), 'text/javascript')
        ->prependFile($this->cdnBackend('/backend/js/vendor/jquery-1.10.2.min.js'), 'text/javascript');

    $this->headLink()
        ->prependStylesheet($this->cdnBackend('/backend/css/gotcms.css'))
        ->prependStylesheet($this->cdnBackend('/backend/css/jquery-ui.gotcms.css'))
        ->prependStylesheet($this->cdnBackend('/backend/css/vendor/jquery.contextMenu.css'))
        ->prependStylesheet($this->cdnBackend('/backend/css/vendor/elfinder.min.css'))
        ->prependStylesheet($this->cdnBackend('/backend/css/vendor/jquery.treeview.css'))
        ->prependStylesheet($this->cdnBackend('/backend/js/vendor/codemirror/lib/codemirror.css'))
        ->prependStylesheet($this->cdnBackend('/backend/css/vendor/jquery-ui-1.10.3.custom.min.css'))
        ->prependStylesheet($this->cdnBackend('/backend/css/bootstrap.min.css'));

    echo $this->headScript();

    echo $this->HeadLink();

    $module = empty($this->routeParams['module']) ? null : strtolower($this->routeParams['module']);
    ?>
</head>
<body<?php if (!empty($module)): ?> id="module-<?php echo $this->escapeHtml($module); ?>"<?php endif; ?>>
    <header class="navbar navbar-default navbar-fixed-top breadcrumbs-fixed" id="navbar">
        <?php echo $this->partial('navigation.phtml', array('active' => $module)); ?>
    </header>

    <div class="main-container container">
        <?php if (empty($module) or in_array($module, array('admin', 'statistics'))): ?>
            <div class="col-lg-12">
        <?php else: ?>
            <div id="sidebar" class="sidebar sidebar-fixed col-lg-2">
                <?php echo $this->partial($module . '-menu.phtml', array('treeview' => $this->treeview, 'moduleMenu' => $this->moduleMenu)); ?>
            </div>
            <div class="col-lg-10 main-content">
        <?php endif; ?>

            <?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('breadcrumb.phtml'); ?>
            <?php echo $this->partial('messages.phtml', array('messages' => $this->flashMessages)); ?>
            <div class="page-content">
                <?php echo $this->content; ?>
            </div>
        </div>
    </div>

    <?php if (!empty($this->routes) or !empty($this->moduleRoutes)): ?>
        <script type="text/javascript">
            <?php if (!empty($this->routes)): ?>
                $(document).ready(function() {
                    Gc.setOption('routes', $.parseJSON('<?php echo $this->escapeJs($this->routes); ?>'));
                    Gc.initDocumentMenu(<?php echo (int)$this->documentId; ?>, '<?php echo $this->escapeJs($this->url('content/document/sort')); ?>');
                });
            <?php endif; ?>

            <?php if (!empty($this->moduleRoutes)): ?>
                $(document).ready(function() {
                    Gc.setOption('moduleRoutes', $.parseJSON('<?php echo $this->escapeJs($this->moduleRoutes); ?>'));
                    Gc.initModuleMenu(<?php echo (int)$this->moduleId; ?>);
                });
            <?php endif; ?>
        </script>
    <?php endif; ?>

    <div id="dialog" title="">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">&nbsp;</span>
            <?php echo $this->escapeHtml($this->translate('These items will be permanently deleted and cannot be recovered. Are you sure?')); ?>
        </p>
    </div>
    <a class="btn-scroll-up btn btn-small btn-inverse" id="btn-scroll-up" href="#">
        <i class="glyphicon glyphicon-open"></i>
    </a>
</body>
</html>
