<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <title><?php echo $this->escapeHtml($this->translate('Admin panel')); ?> - GotCms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300" />

    <meta name="viewport" content="width=device-width">
    <?php
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript()
        ->appendFile($this->cdnBackend('/backend/js/vendor/jquery-1.10.2.min.js'), 'text/javascript')
        ->appendFile($this->cdnBackend('/backend/js/bootstrap.min.js'), 'text/javascript')
        ->appendFile($this->cdnBackend('/backend/js/generic-classes.js', 'text/javascript'))
        ->appendFile($this->cdnBackend('/backend/js/gotcms.js', 'text/javascript'));

    echo $this->HeadLink()
        ->appendStylesheet($this->cdnBackend('/backend/css/bootstrap.min.css'))
        ->appendStylesheet($this->cdnBackend('/backend/css/bootstrap-theme.min.css'))
        ->appendStylesheet($this->cdnBackend('/backend/css/gotcms.css'));
    ?>
</head>
<body class="one-page">
    <div class="container">
        <div class="main-content">
            <div class="row">
                <div class="col-sm-10 col-lg-12">
                    <div class="login-container">
                        <div class="text-center">
                            <h1>
                                <?php echo $this->escapeHtml($this->translate('GotCms Admin')); ?>
                            </h1>
                        </div>

                        <?php echo $this->partial('messages.phtml', array('messages' => $this->flashMessages)); ?>
                        <div class="relative">
                            <?php echo $this->content; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
