<?php
$module = empty($this->layout()->routeParams['module']) ? null : strtolower($this->layout()->routeParams['module']);
?>
<div id="breadcrumbs" class="breadcrumbs breadcrumbs-fixed">
    <?php if (!empty($module) and !in_array($module, array('admin', 'statistics'))): ?>
        <div id="menu-toggler-container">
            <span id="menu-toggler" class="hidden-lg">
                <i class="glyphicon glyphicon-new-window"></i>
                <span class="menu-toggler-text"><?php echo $this->escapeHtml($this->translate('Menu')); ?></span>
            </span>
        </div>
    <?php endif; ?>
    <ul class="breadcrumb">
        <?php foreach ($this->pages as $key => $page): ?>
            <li>
                <?php if (empty($key)): ?>
                    <i class="glyphicon glyphicon-home home-icon"></i>
                <?php endif; ?>

                <?php if ($key < count($this->pages) - 1): ?>
                    <a href="<?php echo $page->getHref(); ?>"><?php echo $this->escapeHtml($this->translate($page->getLabel())); ?></a>
                    <span class="divider">
                        <i class="glyphicon glyphicon-chevron-right arrow-icon"></i>
                    </span>
                <?php else: ?>
                    <?php echo $this->escapeHtml($this->translate($page->getLabel())); ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
