<div id="breadcrumbs" class="breadcrumbs breadcrumbs-fixed">
    <ul class="breadcrumb">
        <?php foreach ($this->pages as $key => $page): ?>
            <li>
                <?php if (empty($key)): ?>
                    <i class="glyphicon glyphicon-home home-icon"></i>
                <?php endif; ?>

                <?php if ($key < count($this->pages) - 1): ?>
                    <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
                    <span class="divider">
                        <i class="glyphicon glyphicon-chevron-right arrow-icon"></i>
                    </span>
                <?php else: ?>
                    <?php echo $page->getLabel(); ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
