<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
if($this->admin())
{
    $permissions = $this->admin()->getRole()->getUserPermissions();
}
?>

<div class="navbar-inner row">
    <div class="col-lg-12">
        <a href="<?php echo $this->url('admin'); ?>" class="brand">
            <small>
                <i class="glyphicon glyphicon-flash"></i>
                <?php echo $this->escapeHtml($this->translate('GotCms Admin')); ?>
            </small>
        </a>

        <div class="pull-right">
            <a href="<?php echo $this->url('config/user/logout'); ?>" class="btn btn-sm btn-warning" title="<?php echo $this->escapeHtml($this->translate('Logout')); ?>">
                <i class="glyphicon glyphicon-off"></i>
            </a>
        </div>

        <div id="navbar-menu">
            <a href="<?php echo $this->url('admin'); ?>" class="btn btn-sm btn-warning<?php if ($this->active == 'admin'): ?> active<?php endif; ?>" title="<?php echo $this->escapeHtml($this->translate('Dashboard')); ?>">
                <i class="glyphicon glyphicon-dashboard"></i>
            </a>

            <?php if (!empty($permissions['content'])): ?>
                <a href="<?php echo $this->url('content'); ?>" class="btn btn-sm btn-warning<?php if ($this->active == 'content'): ?> active<?php endif; ?>" title="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
                    <i class="glyphicon glyphicon-pencil"></i>
                </a>
            <?php endif; ?>

            <?php if (!empty($permissions['development'])): ?>
                <a href="<?php echo $this->url('development'); ?>" class="btn btn-sm btn-warning<?php if ($this->active == 'development'): ?> active<?php endif; ?>" title="<?php echo $this->escapeHtml($this->translate('Development')); ?>">
                    <i class="glyphicon glyphicon-wrench"></i>
                </a>
            <?php endif; ?>

            <?php if (!empty($permissions['modules'])): ?>
                <a href="<?php echo $this->url('module'); ?>" class="btn btn-sm btn-warning<?php if ($this->active == 'module'): ?> active<?php endif; ?>" title="<?php echo $this->escapeHtml($this->translate('Modules')); ?>">
                    <i class="glyphicon glyphicon-cutlery"></i>
                </a>
            <?php endif; ?>

            <?php if (!empty($permissions['stats'])): ?>
                <a href="<?php echo $this->url('statistics'); ?>" class="btn btn-sm btn-warning<?php if ($this->active == 'statistics'): ?> active<?php endif; ?>" title="<?php echo $this->escapeHtml($this->translate('Stats')); ?>">
                    <i class="glyphicon glyphicon-stats"></i>
                </a>
            <?php endif; ?>

            <?php if (!empty($permissions['settings'])): ?>
                <a href="<?php echo $this->url('config'); ?>" class="btn btn-sm btn-warning<?php if ($this->active == 'config'): ?> active<?php endif; ?>" title="<?php echo $this->escapeHtml($this->translate('Configuration')); ?>">
                    <i class="glyphicon glyphicon-cog"></i>
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>

