<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc_Tests
 * @package  ZfModules
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */

namespace Development\Controller;

use Gc\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;
use Gc\Layout\Model as LayoutModel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-15 at 23:50:27.
 *
 * @backupGlobals disabled
 * @backupStaticAttributes disabled
 * @group    ZfModules
 * @category Gc_Tests
 * @package  ZfModules
 */
class LayoutControllerTest extends AbstractHttpControllerTestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    public function setUp()
    {
        $this->init();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::indexAction
     *
     * @return void
     */
    public function testIndexAction()
    {
        $this->dispatch('/admin/development/layout/list');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutList');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::createAction
     *
     * @return void
     */
    public function testCreateAction()
    {
        $this->dispatch('/admin/development/layout/create');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutCreate');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::createAction
     *
     * @return void
     */
    public function testCreateActionWithInvalidPostData()
    {
        $this->dispatch(
            '/admin/development/layout/create',
            'POST',
            array(
            )
        );

        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutCreate');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::createAction
     *
     * @return void
     */
    public function testCreateActionWithPostData()
    {
        $this->dispatch(
            '/admin/development/layout/create',
            'POST',
            array(
                'name' => 'LayoutName',
                'identifier' => 'Identifier',
                'delayoution' => 'Delayoution',
            )
        );
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutCreate');

        LayoutModel::fromIdentifier('Identifier')->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::editAction
     *
     * @return void
     */
    public function testEditActionWithInvalidId()
    {
        $this->dispatch('/admin/development/layout/edit/99999');
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutEdit');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::editAction
     *
     * @return void
     */
    public function testEditAction()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier'
            )
        );
        $layout_model->save();

        $this->dispatch('/admin/development/layout/edit/' . $layout_model->getId());
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutEdit');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::editAction
     *
     * @return void
     */
    public function testEditActionWithInvalidPostData()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier'
            )
        );
        $layout_model->save();

        $this->dispatch(
            '/admin/development/layout/edit/' . $layout_model->getId(),
            'POST',
            array(
            )
        );
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutEdit');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::editAction
     *
     * @return void
     */
    public function testEditActionWithPostData()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier'
            )
        );
        $layout_model->save();

        $this->dispatch(
            '/admin/development/layout/edit/' . $layout_model->getId(),
            'POST',
            array(
                'name' => 'LayoutName',
                'identifier' => 'Identifier',
                'delayoution' => 'Delayoution',
            )
        );
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutEdit');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::deleteAction
     *
     * @return void
     */
    public function testDeleteAction()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier'
            )
        );
        $layout_model->save();
        $this->dispatch('/admin/development/layout/delete/' . $layout_model->getId());
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutDelete');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::deleteAction
     *
     * @return void
     */
    public function testDeleteActionWithInvalidId()
    {
        $this->dispatch('/admin/development/layout/delete/9999');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutDelete');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::uploadAction
     *
     * @return void
     */
    public function testUploadAction()
    {
        $_FILES = array(
            'upload' => array(
                'name' => __DIR__ . '/_files/upload.phtml',
                'type' => 'plain/text',
                'size' => 8,
                'tmp_name' => __DIR__ . '/_files/upload.phtml',
                'error' => 0,
            )
        );

        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier'
            )
        );
        $layout_model->save();
        $this->dispatch('/admin/development/layout/upload/' . $layout_model->getId());
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutUpload');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::uploadAction
     *
     * @return void
     */
    public function testUploadActionWithoutId()
    {
        $_FILES = array(
            'upload' => array(
                'name' => array(
                    'upload.phtml',
                    'test.phtml',
                    'test2.phtml',
                ),
                'type' => array(
                    'plain/text',
                    'plain/text',
                    'plain/text',
                ),
                'size' => array(
                    8,
                    8,
                    8,
                ),
                'tmp_name' => array(
                    __DIR__ . '/_files/upload.phtml',
                    __DIR__ . '/_files/test.phtml',
                    __DIR__ . '/_files/test.phtml',
                ),
                'error' => array(
                    UPLOAD_ERR_OK,
                    UPLOAD_ERR_OK,
                    UPLOAD_ERR_NO_FILE,
                ),
            ),
        );
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'upload'
            )
        );
        $layout_model->save();
        $this->dispatch('/admin/development/layout/upload');
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutUpload');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::uploadAction
     *
     * @return void
     */
    public function testUploadActionWithEmptyFilesData()
    {
        $_FILES = array('upload' => array());
        $this->dispatch('/admin/development/layout/upload');
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutUpload');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::uploadAction
     *
     * @return void
     */
    public function testUploadActionWithInvalidId()
    {
        $this->dispatch('/admin/development/layout/upload/9999');
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutUpload');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::downloadAction
     *
     * @return void
     */
    public function testDownloadAction()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier',
                'content' => 'Test',
            )
        );
        $layout_model->save();
        $this->dispatch('/admin/development/layout/download/' . $layout_model->getId());
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutDownload');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::downloadAction
     *
     * @return void
     */
    public function testDownloadActionWithEmptyContent()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier',
            )
        );
        $layout_model->save();
        $this->dispatch('/admin/development/layout/download/' . $layout_model->getId());
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutDownload');

        $layout_model->delete();
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::downloadAction
     *
     * @return void
     */
    public function testDownloadActionWithInvalidId()
    {
        $this->dispatch('/admin/development/layout/download/9999');
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutDownload');
    }

    /**
     * Test
     *
     * @covers Development\Controller\LayoutController::downloadAction
     *
     * @return void
     */
    public function testDownloadActionWithoutId()
    {
        $layout_model = LayoutModel::fromArray(
            array(
                'name' => 'LayoutName',
                'identifier' => 'LayoutIdentifier',
                'content' => 'Content',
            )
        );
        $layout_model->save();
        $this->dispatch('/admin/development/layout/download');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Development');
        $this->assertControllerName('LayoutController');
        $this->assertControllerClass('LayoutController');
        $this->assertMatchedRouteName('layoutDownload');

        $layout_model->delete();
    }
}
