<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Content
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) http://rambaudpierre.fr
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>

<h1><?php echo $this->escapeHtml($this->translate('Create your own website')); ?></h1>
<section>
    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Content')); ?></h2>
        <p><?php echo $this->escapeHtml($this->translate('You can create, edit, copy, cut and paste document by right-clicking on Website or children documents.')); ?></p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Files')); ?></h2>
        <p><?php echo $this->escapeHtml($this->translate('elFinder is an open-source file manager for web. And with you can manage your files, folders and others data of this website.')); ?></p>
        <p><?php echo $this->escapeHtml($this->translate('He has many options like an window explorer. Be careful when deleting data, it is not reversible.')); ?></p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Translations')); ?></h2>
        <p><?php echo $this->escapeHtml($this->translate('Edit translation for frontend and backend.')); ?></p>
    </article>
</section>
