<ul>
    <li><a href="#tabs-1"><?php echo $this->escape($this->translator('Infos')); ?></a></li>
    <li><a href="#tabs-2"><?php echo $this->escape($this->translator('Views')); ?></a></li>
    <li><a href="#tabs-3"><?php echo $this->escape($this->translator('Properties')); ?></a></li>
    <li><a href="#tabs-4"><?php echo $this->escape($this->translator('Tabs')); ?></a></li>
</ul>
<?php $infos_form = $this->element->infos; ?>
<?php $views_form = $this->element->views; ?>
<?php $tabs_form = $this->element->tabs->getSubForms(); ?>
<form id="development-form" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url('documentTypeAdd'); ?>" method="post">
    <dl id="tabs-1">
        <dt id="name-label">
            <label for="infos-name" class="optional"><?php echo $this->escape($this->translator('Name')); ?></label>
        </dt>
        <dd id="name-element">
            <input type="text" name="infos[name]" id="infos-name" value="<?php echo $infos_form->getValue('name'); ?>">
        </dd>
        <dt id="description-label">
            <label for="infos-description" class="optional"><?php echo $this->escape($this->translator('Description')); ?></label>
        </dt>
        <dd id="description-element">
            <input type="text" name="infos[description]" id="infos-description" value="<?php echo $infos_form->getValue('description'); ?>">
        </dd>
        <dt id="icon_id-label">
            <label for="infos-icon_id" class="optional"><?php echo $this->escape($this->translator('Icon')); ?></label>
        </dt>
        <dd id="icon_id-element">
            <select name="infos[icon_id]" id="infos-icon_id">

            </select>
        </dd>
    </dl>

    <dl id="tabs-2">
        <dt id="default_view_id-label">
            <label for="views-default_view_id" class="required"><?php echo $this->escape($this->translator('Default view')); ?></label>
        </dt>

        <dd id="default_view_id-element">
            <select name="views[default_view]" id="views-default_view">
                <option value=""><?php echo $this->escape($this->translator('-- Select --')); ?></option>
                <?php foreach($views as $view_id => $view_name): ?>
                    <option value="<?php echo $view_id; ?>"<?php if($views_form->getValue('default_view') == $view_id): ?> selected="selected"<?php endif; ?>><?php echo $this->escape($view_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt id="all_views-label">
            <label for="views-all_views" class="optional"><?php echo $this->escape($this->translator('Add view')); ?></label>
        </dt>
        <dd id="all_views-element">
            <select name="views[available_views]" id="views-available_views" multiple="multiple">
                <?php foreach($views as $view_id => $view_name): ?>
                    <option value="<?php echo $view_id; ?>"><?php echo $this->escape($view_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt id="add-label">&nbsp;</dt>
        <dd id="add-element">
            <button name="views[add]" id="views-add" type="button" class="button-add button-add-view"><?php echo $this->escape($this->translator('Add view')); ?></button>
        </dd>
    </dl>

    <dl id="tabs-3">
        <dt id="name-label">
            <label for="properties-name" class="optional"><?php echo $this->escape($this->translator('Name')); ?></label>
        </dt>
        <dd id="name-element">
            <input type="text" name="properties[name]" id="properties-name" value="">
        </dd>
        <dt id="identifier-label">
            <label for="properties-identifier" class="optional"><?php echo $this->escape($this->translator('Identifier')); ?></label>

        </dt>
        <dd id="identifier-element">
            <input type="text" name="properties[identifier]" id="properties-identifier" value="">
        </dd>
        <dt id="tab-label">
            <label for="properties-tab" class="required"><?php echo $this->escape($this->translator('Tab')); ?></label>
        </dt>
        <dd id="tab-element">
            <select name="properties[tab]" id="properties-tab" class="select-tab">
                <option value="" label="-- Select tab --" selected="selected">-- Select tab --</option>
            </select>
        </dd>

        <dt id="datatype-label">
            <label for="properties-datatype" class="required"><?php echo $this->escape($this->translator('Datatype')); ?></label>
        </dt>
        <dd id="datatype-element">
            <select name="properties[datatype]" id="properties-datatype" class="select-datatype">
                <option value=""><?php echo $this->escape($this->translator('-- Select --')); ?></option>
                <?php foreach($datatypes as $datatype_id => $datatype_name): ?>
                    <option value="<?php echo $datatype_id; ?>"><?php echo $this->escape($datatype_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt id="description-label">
            <label for="properties-description" class="optional"><?php echo $this->escape($this->translator('Description')); ?></label>
        </dt>
        <dd id="description-element">
            <input type="text" name="properties[description]" id="properties-description" value="">
        </dd>
        <dt id="required-label">
            <label for="properties-required" class="optional"><?php echo $this->escape($this->translator('Required')); ?></label>
        </dt>

        <dd id="required-element">
            <input type="checkbox" name="properties[required]" id="properties-required" value="1">
        </dd>
        <dt id="add-label">&nbsp;</dt>
        <dd id="add-element">
            <button name="properties[add]" id="property_add" type="button" class="button-add button-add-property"><?php echo $this->escape($this->translator('Add property')); ?></button>
        </dd>
        <dt><?php echo $this->escape($this->translator('Properties')); ?></dt>
        <dd>
            <div id="properties-tabs-content" class="tabs">
                <ul>
                    <?php $idx = 1; ?>
                    <?php foreach($tabs_form as $form): ?>
                        <li>
                            <?php $name = $form->getElement('name')->getValue(); ?>
                            <a href="#tabs-properties-<?php echo $idx++; ?>">
                                <?php echo $name; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <?php $idx = 1; ?>
                <?php foreach($tabs_form as $form): ?>
                    <div id="tabs-properties-<?php echo $idx++; ?>">
                        <ul>
                            <?php foreach($properties_form as $property): ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endforeach; ?>
            </div>
        </dd>
    </dl>

    <dl id="tabs-4">
        <dt id="addname-label">
            <label for="tabs-addname" class="optional"><?php echo $this->escape($this->translator('Name')); ?></label>
        </dt>
        <dd id="addname-element">
            <input type="text" name="tabs[addname]" id="tabs-addname" value="">
        </dd>
        <dt id="adddescription-label">
            <label for="tabs-adddescription" class="optional"><?php echo $this->escape($this->translator('Description')); ?></label>
        </dt>
        <dd id="adddescription-element">
            <input type="text" name="tabs[adddescription]" id="tabs-adddescription" value="">
        </dd>
        <dt id="add-label">&nbsp;</dt>
        <dd id="add-element">
            <button name="tabs[add]" id="tabs-add" type="button" class="button-add button-add-tab"><?php echo $this->escape($this->translator('Add Tab')); ?></button>
        </dd>

        <dt><?php echo $this->escape($this->translator('Tabs')); ?></dt>
        <dd>
            <ul id="tabs" class="sortable ui-sortable">
            <?php foreach($tabs_form as $form): ?>
                <li>
                    <?php $name = $form->getElement('name')->getValue(); ?>
                    <?php $description = $form->getElement('description')->getValue(); ?>
                    <?php $tab_id = $form->getElement('description')->getValue(); ?>
                    <input type="hidden" value="<?php echo $name; ?>" name="tab[<?php echo $tab_id; ?>][name]">
                    <input type="hidden" value="<?php echo $description; ?>" name="tab[<?php echo $tab_id; ?>][description]">
                    <span><?php echo $name; ?></span>
                    <span><?php echo $description; ?></span>
                    <button class="delete-tab" type="button">delete</button>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
    </dl>

    <div>
        <input type="submit" name="submit" id="submit" value="Submit">
    </div>
</form>
