<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Module
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<ul class="nav nav-list dropdown">
<?php if ($this->acl('development', 'document-type')): ?>
    <li>
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Modules')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <?php if ($this->acl('modules', 'install')): ?>
                <li>
                    <a href="<?php echo $this->url('module/install'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('Install')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <li>
                <a href="<?php echo $this->url('module'); ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('List')); ?>
                </a>
            </li>
        </ul>
    </li>
<?php endif; ?>
</ul>

<?php if (!empty($this->layout()->moduleMenu)): ?>
    <?php echo $this->partial($this->layout()->moduleMenu . '.phtml'); ?>
<?php endif; ?>
