<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc_Tests
 * @package  ZfModules
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */

namespace Config\Controller;

use Gc\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;
use Gc\User\Role\Model as RoleModel;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-15 at 23:51:06.
 *
 * @group    ZfModules
 * @category Gc_Tests
 * @package  ZfModules
 */
class RoleControllerTest extends AbstractHttpControllerTestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    public function setUp()
    {
        $this->init();
    }

    /**
     * Test
     *
     * @return void
     */
    public function testIndexAction()
    {
        $this->dispatch('/admin/config/user/role');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testCreateAction()
    {
        $this->dispatch('/admin/config/user/role/create');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/create');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testCreateActionWithPostData()
    {
        $this->dispatch(
            '/admin/config/user/role/create',
            'POST',
            array(
                'name' => 'RoleCreateTest',
                'description' => 'Description'
            )
        );
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/create');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testCreateActionWithWrongPostData()
    {
        $this->dispatch(
            '/admin/config/user/role/create',
            'POST',
            array(
            )
        );
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/create');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testDeleteAction()
    {
        $roleModel = RoleModel::fromArray(
            array(
                'name'        => 'RoleTest',
                'description' => 'Description',
            )
        );
        $roleModel->save();

        $this->dispatch('/admin/config/user/role/delete/' . $roleModel->getId());
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/delete');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testDeleteActionWithWrongId()
    {
        $this->dispatch('/admin/config/user/role/delete/9999');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/delete');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testEditAction()
    {
        $roleModel = RoleModel::fromArray(
            array(
                'name'        => 'RoleTest',
                'description' => 'Description',
            )
        );
        $roleModel->save();

        $this->dispatch('/admin/config/user/role/edit/' . $roleModel->getId());
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/edit');

        $roleModel->delete();
    }

    /**
     * Test
     *
     * @return void
     */
    public function testEditActionWithPostData()
    {
        $roleModel = RoleModel::fromArray(
            array(
                'name'        => 'RoleTest',
                'description' => 'Description',
            )
        );
        $roleModel->save();

        $this->dispatch(
            '/admin/config/user/role/edit/' . $roleModel->getId(),
            'POST',
            array(
                'name'        => 'RoleTest',
                'description' => 'Description',
            )
        );
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/edit');

        $roleModel->delete();
    }

    /**
     * Test
     *
     * @return void
     */
    public function testEditActionWithWrongPostData()
    {
        $roleModel = RoleModel::fromArray(
            array(
                'name'        => 'RoleTest',
                'description' => 'Description',
            )
        );
        $roleModel->save();

        $this->dispatch(
            '/admin/config/user/role/edit/' . $roleModel->getId(),
            'POST',
            array(
            )
        );
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/edit');

        $roleModel->delete();
    }

    /**
     * Test
     *
     * @return void
     */
    public function testEditActionWithWrongId()
    {
        $this->dispatch('/admin/config/user/role/edit/9999');
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('Config');
        $this->assertControllerName('RoleController');
        $this->assertControllerClass('RoleController');
        $this->assertMatchedRouteName('config/user/role/edit');
    }
}
