<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<h1><?php echo $this->escapeHtml($this->translate('Make the M.V.C be with you')); ?></h1>
<section>
    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Views')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Create, edit, and delete views.')); ?><br />
            <?php echo $this->escapeHtml($this->translate('Insert in document types, if you want to get and use property write: $this->propertyIdentifier')); ?>
        </p>
        <p><?php echo $this->escapeHtml($this->translate("There's lot of Helper you can use. Those Zend Framework and GotCms, refer to documentation if you want more information."));?></p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Layouts')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Work like views, you can get properties, use helpers, and if you want to integrate children (view) write: $this->content.')); ?><br />
        </p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Datatypes')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Data can be stored in. Create your own datatype, edit configuration and insert it in document type.')); ?><br />
        </p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Document types')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('This is a document pattern. Sort by tabs, insert datatypes and specify availables views.')); ?><br />
        </p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Scripts')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Work like Zend Framework controllers, you can get the request, response and controller plugins.')); ?><br />
        </p>
    </article>
</section>
