<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Name')); ?></th>
        <th><?php echo $this->escape($this->translator('Description')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->roles as $role): ?>
        <tr>
            <td><?php echo $role->getId(); ?></td>
            <td><?php echo $this->escape($role->getName()); ?></td>
            <td><?php echo $this->escape($role->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('userRoleEdit', array('id' => $role->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('userRoleDelete', array('id' => $role->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>" />
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

