<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<div class="page-header position-relative">
    <h1>
        <?php echo $this->escapeHtml($this->translate('Installation currently finish')); ?>
    </h1>
</div>

<ul id="installer" class="list-group">
    <li class="list-group-item" id="c-db"><?php echo $this->escapeHtml($this->translate('Create database')); ?></li>
    <li class="list-group-item" id="i-d"><?php echo $this->escapeHtml($this->translate('Insert data')); ?></li>
    <li class="list-group-item" id="c-uar"><?php echo $this->escapeHtml($this->translate('Create users and roles')); ?></li>
    <li class="list-group-item" id="it"><?php echo $this->escapeHtml($this->translate('Install template')); ?></li>
    <li class="list-group-item" id="c-cf"><?php echo $this->escapeHtml($this->translate('Create configuration file')); ?></li>
</ul>

<div id="installation-data" class="alert">&nbsp;</div>
<script type="text/javascript">
    $(document).ready(function() {
        var $data = ['c-db', 'i-d', 'c-uar', 'it', 'c-cf'],
        $progressClass = 'install-in-progress',
        $completeClass = 'install-complete',
        $errorClass    = 'install-error',
        $installHtml   = $('#installation-data');

        function nextStep($step) {
            if ($data[$step] == undefined) {
                return false;
            }

            var $object = $('#' + $data[$step]);
            $object.addClass($progressClass);

            $.ajax({
                url:      '<?php echo $this->escapeJs($this->url('install/complete')); ?>',
                dataType: 'json',
                data:     {step: $data[$step]},
                type:     'POST',
                error:    function() {
                    $installHtml
                        .addClass('alert-danger')
                        .html('<?php echo $this->escapeJs($this->translate('The request has been stopped, please refresh the page')); ?>');
                    $object.removeClass($progressClass).addClass($errorClass);
                },
                success:  function(data) {
                    if (data.success == true) {
                        $object.removeClass($progressClass).addClass($completeClass);
                        nextStep(++$step);
                    } else {
                        $installHtml
                            .html(data.message);
                        if ($data[$step] == 'c-cf') {
                            $installHtml.addClass('alert-success')
                            $object.removeClass($progressClass).addClass($completeClass);
                        } else {
                            $installHtml.addClass('alert-danger')
                            $object.removeClass($progressClass).addClass($errorClass);
                        }
                    }
                }
            });
        }

        nextStep(0);
    });
</script>
