<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>

<h2><?php echo $this->escapeHtml($this->translate('Installation currently finish')); ?></h2>
<ul>
    <li id="c-db" class="active"><?php echo $this->escapeHtml($this->translate('Create database')); ?></li>
    <li id="i-d"><?php echo $this->escapeHtml($this->translate('Insert data')); ?></li>
    <li id="c-uar"><?php echo $this->escapeHtml($this->translate('Create users and roles')); ?></li>
    <li id="c-cf"><?php echo $this->escapeHtml($this->translate('Create configuration file')); ?></li>
</ul>

<div id="installation-data">
    <img src="/images/treeview/ajax-loader.gif">
</div>
<script type="text/javascript">
    $(document).ready(function()
    {
        $data = ['c-db', 'i-d', 'c-uar', 'c-cf'];

        function nextStep($step)
        {
            if($data[$step] == undefined)
            {
                return false;
            }

            $.ajax({
                url: '<?php echo $this->escapeJs($this->url('installComplete')); ?>',
                dataType: 'json',
                data: {step: $data[$step]},
                type: 'POST',
                success: function(data)
                {
                    if(data.success == true)
                    {
                        nextStep(++$step);
                    }
                    else
                    {
                        $('#installation-data').html(data.message);
                    }
                }
            });
        }

        nextStep(0);
    });
</script>
