<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<div class="page-header position-relative">
    <h1>
        <?php echo $this->escapeHtml($this->translate('Installation currently finish')); ?>
    </h1>
</div>

<ul id="installer">
    <li id="c-db"><?php echo $this->escapeHtml($this->translate('Create database')); ?></li>
    <li id="i-d"><?php echo $this->escapeHtml($this->translate('Insert data')); ?></li>
    <li id="c-uar"><?php echo $this->escapeHtml($this->translate('Create users and roles')); ?></li>
    <li id="it"><?php echo $this->escapeHtml($this->translate('Install template')); ?></li>
    <li id="c-cf"><?php echo $this->escapeHtml($this->translate('Create configuration file')); ?></li>
</ul>

<div id="installation-data">&nbsp;</div>
<script type="text/javascript">
    $(document).ready(function() {
        $data = ['c-db', 'i-d', 'c-uar', 'it', 'c-cf'];

        function nextStep($step) {
            if ($data[$step] == undefined) {
                return false;
            }

            $('#' + $data[$step]).addClass('progress');

            $.ajax({
                url: '<?php echo $this->escapeJs($this->url('install/complete')); ?>',
                dataType: 'json',
                data: {step: $data[$step]},
                type: 'POST',
                success: function(data) {
                    if (data.success == true) {
                        $('#' + $data[$step]).removeClass('progress').addClass('complete');
                        nextStep(++$step);
                    } else {
                        if ($data[$step] == 'c-cf') {
                            $('#' + $data[$step]).removeClass('progress').addClass('complete');
                        } else {
                            $('#' + $data[$step]).removeClass('progress').addClass('error');
                        }

                        $('#installation-data').html(data.message);
                    }
                }
            });
        }

        nextStep(0);
    });
</script>
