<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<h2><?php echo $this->escape($this->translator('Database configuration')); ?></h2>

<?php if(!empty($this->messages)): ?>
    <ul>
        <?php foreach($this->messages as $message): ?>
            <li><?php echo $this->escape($this->translator($message)); ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<?php $elements = $this->form->getElements(); ?>
<?php $errors = $this->form->getMessages(); ?>
<?php foreach($elements as $element): ?>
    <div>
        <label class="required" for="name"><?php echo $this->escape($this->translator($element->getAttribute('label'))); ?></label>

        <?php echo $this->formElement($element); ?>

        <?php if(!empty($errors[$element->getAttribute('name')])): ?>
            <?php echo $this->formErrors($errors[$element->getAttribute('name')]); ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
