<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<div class="page-header position-relative">
    <h1>
        <?php echo $this->escapeHtml($this->translate('Database configuration')); ?>
    </h1>
</div>

<?php if (!empty($this->messages)): ?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach ($this->messages as $message): ?>
                <li><?php echo $this->escapeHtml($this->translate($message)); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php $elements = $this->form->getElements(); ?>
<div class="form-horizontal">
    <?php foreach ($elements as $element): ?>
        <div class="form-group">
            <label class="control-label required col-lg-2" for="<?php echo $element->getAttribute('id'); ?>"><?php echo $this->escapeHtml($this->translate($element->getAttribute('label'))); ?></label>
            <div class="col-lg-10">
                <?php echo $this->formElement($element); ?>
                <?php echo $this->formElementErrors($element); ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>
