<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<div class="page-header position-relative">
    <h1>
        <?php echo $this->escapeHtml($this->translate('License')); ?>
    </h1>
</div>

<div class="form-group">
    <textarea class="form-control" readonly="readonly" rows="20">
        <?php echo $this->escapeHtml($this->license); ?>
    </textarea>
</div>

<div class="form-group">
    <label class="control-label">
        <?php echo $this->formElement($this->form->get('accept-license')); ?>
        <?php echo $this->escapeHtml($this->translate('You must accept this license for continue to install this software.')); ?>
    </label>
</div>
