<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<h2><?php echo $this->escapeHtml($this->translate('Steps:')); ?></h2>
<ul>
    <li<?php if($this->currentRoute == 'install'): ?> class="active"<?php endif; ?>><?php echo $this->escapeHtml($this->translate('Language')); ?></li>
    <li<?php if($this->currentRoute == 'installLicense'): ?> class="active"<?php endif; ?>><?php echo $this->escapeHtml($this->translate('License')); ?></li>
    <li<?php if($this->currentRoute == 'installCheckConfig'): ?> class="active"<?php endif; ?>><?php echo $this->escapeHtml($this->translate('Pre-configuration')); ?></li>
    <li<?php if($this->currentRoute == 'installDatabase'): ?> class="active"<?php endif; ?>><?php echo $this->escapeHtml($this->translate('Database')); ?></li>
</ul>
