<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

$routes = array(
    'install',
    'install/license',
    'install/check-config',
    'install/database',
    'install/configuration',
);
$step = array_search($this->currentRoute, $routes);
if (empty($this->currentRoute)) {
    $step = 5;
}

?>
<ul class="nav nav-list">
    <li class="open active">
        <a href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Steps:')); ?></span>
        </a>
        <ul class="submenu">
            <li<?php if ($this->currentRoute == $routes[0]): ?> class="active"<?php elseif($step > 0): ?> class="done"<?php endif; ?>>
                <a href="<?php if($step > 0): ?><?php echo $this->url('install'); ?><?php else: ?>#<?php endif; ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('Language')); ?>
                </a>
            </li>
            <li<?php if ($this->currentRoute == $routes[1]): ?> class="active"<?php elseif($step > 1): ?> class="done"<?php endif; ?>>
                <a href="<?php if($step > 1): ?><?php echo $this->url('install/license'); ?><?php else: ?>#<?php endif; ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('License')); ?>
                </a>
            </li>
            <li<?php if ($this->currentRoute == $routes[2]): ?> class="active"<?php elseif($step > 2): ?> class="done"<?php endif; ?>>
                <a href="<?php if($step > 2): ?><?php echo $this->url('install/check-config'); ?><?php else: ?>#<?php endif; ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('Pre-configuration')); ?>
                </a>
            </li>
            <li<?php if ($this->currentRoute == $routes[3]): ?> class="active"<?php elseif($step > 3): ?> class="done"<?php endif; ?>>
                <a href="<?php if($step > 3): ?><?php echo $this->url('install/database'); ?><?php else: ?>#<?php endif; ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('Database')); ?>
                </a>
            </li>
            <li<?php if ($this->currentRoute == $routes[4]): ?> class="active"<?php elseif($step >= 4): ?> class="done"<?php endif; ?>>
                <a href="<?php if($step > 4): ?><?php echo $this->url('install/configuration'); ?><?php else: ?>#<?php endif; ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('Configuration')); ?>
                </a>
            </li>
        </ul>
    </li>
</ul>
