<h2>..:: <?php echo $this->escape($this->translate('Managing Users')); ?> ::..</h2>

<ul>
    <li><a href="" title=""><?php echo $this->escape($this->translate('Users list')); ?></a></li>
    <li><a href="" title=""><?php echo $this->escape($this->translate('Add')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translate('Website Configuration')); ?> ::..</h2>

<ul>
    <li><a href="" title=""><?php echo $this->escape($this->translate('Managing Users')); ?></a></li>
    <li><a href="" title=""><?php echo $this->escape($this->translate('Managing Users')); ?></a></li>
</ul>
