<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Name')); ?></th>
        <th><?php echo $this->escape($this->translator('Identifier')); ?></th>
        <th><?php echo $this->escape($this->translator('Description')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->documents as $document): ?>
        <tr>
            <td><?php echo $document->getId(); ?></td>
            <td><?php echo $this->escape($document->getName()); ?></td>
            <td><?php echo $this->escape($document->getIdentifier()); ?></td>
            <td><?php echo $this->escape($document->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('documentTypeEdit', array('id' => $document->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('documentTypeDelete', array('id' => $document->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>">
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

