<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Name')); ?></th>
        <th><?php echo $this->escape($this->translator('Identifier')); ?></th>
        <th><?php echo $this->escape($this->translator('Description')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->views as $view): ?>
        <tr>
            <td><?php echo $view->getId(); ?></td>
            <td><?php echo $this->escape($view->getName()); ?></td>
            <td><?php echo $this->escape($view->getIdentifier()); ?></td>
            <td><?php echo $this->escape($view->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('viewEdit', array('id' => $view->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('viewDelete', array('id' => $view->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>" />
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

