<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/GPL http://www.gnu.org/licenses/gpl-3.0.html
 * @link     http://www.got-cms.com
 * @license  http://www.gnu.org/licenses/gpl-3.0.html
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Name')); ?></th>
        <th><?php echo $this->escape($this->translator('Identifier')); ?></th>
        <th><?php echo $this->escape($this->translator('Description')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->views as $view): ?>
        <tr>
            <td><?php echo $view->getId(); ?></td>
            <td><?php echo $this->escape($view->getName()); ?></td>
            <td><?php echo $this->escape($view->getIdentifier()); ?></td>
            <td><?php echo $this->escape($view->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('viewEdit', array('id' => $view->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('viewDelete', array('id' => $view->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>">
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

