<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Config
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>
<form class="relative form-horizontal" action="<?php echo $this->escapeHtml($this->form->getAttribute('action')); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label class="required control-label col-lg-2" for="name"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        <div class="col-lg-10">
            <input type="text" class="form-control" value="<?php echo $this->escapeHtml($this->form->getValue('name')); ?>" id="name" name="name">
        </div>
    </div>

    <div class="form-group">
        <label class="optional control-label col-lg-2" for="description"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
        <div class="col-lg-10">
            <input type="text" class="form-control" value="<?php echo $this->escapeHtml($this->form->getValue('description')); ?>" id="description" name="description">
        </div>
    </div>


    <?php $permissions = $this->form->getValue('permissions'); ?>
    <dl id="role-list">
        <?php foreach ($permissions as $resource => $permissions): ?>
            <dt><h2><?php echo $this->escapeHtml($this->translate(ucfirst($resource))); ?></h2></dt>
            <dd>
                <dl>
                    <?php foreach ($permissions as $name => $perms): ?>
                        <?php if (count($perms) > 1): ?>
                            <dt><h3><?php echo $this->escapeHtml($this->translate(ucfirst($name))); ?></h3></dt>
                        <?php endif; ?>

                        <?php foreach($perms as $permission) :?>
                            <dd>
                                <label class="optional" for="permissions-<?php echo (int)$permission['id']; ?>">
                                    <?php echo $this->escapeHtml($this->translate($permission['name'])); ?>
                                </label>
                                <div class="input-checkbox">
                                    <input type="checkbox" class="input-checkbox" value="1" <?php if ($permission['value']): ?>checked="checked" <?php endif; ?>id="permissions-<?php echo (int)$permission['id']; ?>" name="permissions[<?php echo (int)$permission['id']; ?>]">
                                    <label for="permissions-<?php echo (int)$permission['id']; ?>"></label>
                                </div>
                            </dd>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </dl>
            </dd>
        <?php endforeach; ?>
    </dl>

    <input id="input-save" type="submit" class="btn btn-warning" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" id="submit" name="submit">
</form>

<script type="text/javascript">
$(function(){
    Gc.saveCommand();
    Gc.checkDataChanged();
    Gc.initRoles();
});
</script>
