<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Config
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>
<form class="simple-form" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <div>
        <label class="required" for="email"><?php echo $this->escapeHtml($this->translate('Email')); ?></label>
        <input type="email" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('email')); ?>" id="email" name="email">

        <?php echo $this->formElementErrors($this->form->get('email')); ?>
    </div>
    <div>
        <label class="optional" for="login"><?php echo $this->escapeHtml($this->translate('Login')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('login')); ?>" id="login" name="login">

        <?php echo $this->formElementErrors($this->form->get('login')); ?>
    </div>
    <div>
        <label class="required" for="password"><?php echo $this->escapeHtml($this->translate('Password')); ?></label>
        <input type="password" autocomplete="off" class="input-text" value="" id="password" name="password">

        <?php echo $this->formElementErrors($this->form->get('password')); ?>
    </div>
    <div>
        <label class="required" for="password_confirm"><?php echo $this->escapeHtml($this->translate('Password Confirm')); ?></label>
        <input type="password" autocomplete="off" class="input-text" value="" id="password_confirm" name="password_confirm">

        <?php echo $this->formElementErrors($this->form->get('password_confirm')); ?>
    </div>
    <div>
        <label class="required" for="lastname"><?php echo $this->escapeHtml($this->translate('Lastname')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('lastname')); ?>" id="lastname" name="lastname">

        <?php echo $this->formElementErrors($this->form->get('lastname')); ?>
    </div>
    <div>
        <label class="required" for="firstname"><?php echo $this->escapeHtml($this->translate('Firstname')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('firstname')); ?>" id="firstname" name="firstname">

        <?php echo $this->formElementErrors($this->form->get('firstname')); ?>
    </div>
    <div>
        <label class="required" for="user_acl_role_id"><?php echo $this->escapeHtml($this->translate('Role')); ?></label>
        <select class="input-select" id="user_acl_role_id" name="user_acl_role_id">
            <?php $options = $this->form->get('user_acl_role_id')->getValueOptions(); ?>
            <?php foreach($options as $option_id => $option_value): ?>
                <option <?php if($option_id == $this->form->getValue('user_acl_role_id')): ?>selected="selected" <?php endif; ?>label="<?php echo $this->escapeHtml($this->translate($option_value)); ?>" value="<?php echo (int) $option_id; ?>"><?php echo $this->escapeHtml($this->translate($option_value)); ?></option>
            <?php endforeach; ?>
        </select>

        <?php echo $this->formElementErrors($this->form->get('user_acl_role_id')); ?>
    </div>
    <div>
        <input type="submit" class="input-submit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" id="submit" name="submit">
    </div>
</form>
