<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php $errors = $this->form->getMessages(); ?>
<form class="simple-form" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <div>
        <label class="required" for="email"><?php echo $this->escape($this->translator('Email')); ?></label>
        <input type="email" class="input-text" value="<?php echo $this->escape($this->form->getValue('email')); ?>" id="email" name="email">
        <?php if(!empty($errors['email'])): ?>
            <?php echo $this->formErrors($errors['email']); ?>
        <?php endif; ?>
    </div>
    <div>
        <label class="optional" for="login"><?php echo $this->escape($this->translator('Login')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escape($this->form->getValue('login')); ?>" id="login" name="login">
        <?php if(!empty($errors['login'])): ?>
            <?php echo $this->formErrors($errors['login']); ?>
        <?php endif; ?>
    </div>
    <div>
        <label class="required" for="password"><?php echo $this->escape($this->translator('Password')); ?></label>
        <input type="password" autocomplete="off" class="input-text" value="" id="password" name="password">
        <?php if(!empty($errors['password'])): ?>
            <?php echo $this->formErrors($errors['password']); ?>
        <?php endif; ?>
    </div>
    <div>
        <label class="required" for="password_confirm"><?php echo $this->escape($this->translator('Password Confirm')); ?></label>
        <input type="password" autocomplete="off" class="input-text" value="" id="password_confirm" name="password_confirm">
        <?php if(!empty($errors['password_confirm'])): ?>
            <?php echo $this->formErrors($errors['password_confirm']); ?>
        <?php endif; ?>
    </div>
    <div>
        <label class="required" for="lastname"><?php echo $this->escape($this->translator('Lastname')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escape($this->form->getValue('lastname')); ?>" id="lastname" name="lastname">
        <?php if(!empty($errors['lastname'])): ?>
            <?php echo $this->formErrors($errors['lastname']); ?>
        <?php endif; ?>
    </div>
    <div>
        <label class="required" for="firstname"><?php echo $this->escape($this->translator('Firstname')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escape($this->form->getValue('firstname')); ?>" id="firstname" name="firstname">
        <?php if(!empty($errors['firstname'])): ?>
            <?php echo $this->formErrors($errors['firstname']); ?>
        <?php endif; ?>
    </div>
    <div>
        <label class="required" for="user_acl_role_id"><?php echo $this->escape($this->translator('Role')); ?></label>
        <select class="input-select" id="user_acl_role_id" name="user_acl_role_id">
            <?php $options = $this->form->get('user_acl_role_id')->getAttribute('options'); ?>
            <?php foreach($options as $option_id => $option_value): ?>
                <option <?php if($option_id == $this->form->getValue('user_acl_role_id')): ?>selected="selected" <?php endif; ?>label="<?php echo $this->escape($this->translator($option_value)); ?>" value="<?php echo (int) $option_id; ?>"><?php echo $this->escape($this->translator($option_value)); ?></option>
            <?php endforeach; ?>
        </select>
        <?php if(!empty($errors['user_acl_role_id'])): ?>
            <?php echo $this->formErrors($errors['user_acl_role_id']); ?>
        <?php endif; ?>
    </div>
    <div>
        <input type="submit" class="input-submit" value="<?php echo $this->escape($this->translator('Save')); ?>" id="submit" name="submit">
    </div>
</form>
