<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Lastname')); ?></th>
        <th><?php echo $this->escape($this->translator('Firstname')); ?></th>
        <th><?php echo $this->escape($this->translator('Email')); ?></th>
        <th><?php echo $this->escape($this->translator('Login')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->users as $user): ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $this->escape($user->getName()); ?></td>
            <td><?php echo $this->escape($user->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('userEdit', array('id' => $user->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('userDelete', array('id' => $user->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>">
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

