<h2>..:: <?php echo $this->escape($this->translator('Managing Users')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('userList'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
    <li><a href="<?php echo $this->url('userCreate'); ?>" title=""><?php echo $this->escape($this->translator('Create')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Managing Roles')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('userRole'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
    <li><a href="<?php echo $this->url('userRoleCreate'); ?>" title=""><?php echo $this->escape($this->translator('Create')); ?></a></li>
</ul>
