<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/GPL http://www.gnu.org/licenses/gpl-3.0.html
 * @link     http://www.got-cms.com
 * @license  http://www.gnu.org/licenses/gpl-3.0.html
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<h2>..:: <?php echo $this->escape($this->translator('Managing configuration')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('configGeneral'); ?>" title=""><?php echo $this->escape($this->translator('General')); ?></a></li>
    <li><a href="<?php echo $this->url('configSystem'); ?>" title=""><?php echo $this->escape($this->translator('System')); ?></a></li>
    <li><a href="<?php echo $this->url('configServer'); ?>" title=""><?php echo $this->escape($this->translator('Server')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Managing Users')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('userList'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
    <li><a href="<?php echo $this->url('userCreate'); ?>" title=""><?php echo $this->escape($this->translator('Create')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Managing Roles')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('userRole'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
    <li><a href="<?php echo $this->url('userRoleCreate'); ?>" title=""><?php echo $this->escape($this->translator('Create')); ?></a></li>
</ul>
