<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<a href="<?php echo $this->url('layoutDownload', array('id' => $this->layoutId)); ?>"><?php echo $this->escapeHtml($this->translate('Download file')); ?></a>
<a href="#" id="upload-link"><?php echo $this->escapeHtml($this->translate('Upload file')); ?></a>

<form class="hide" id="form-content" action="<?php echo $this->url('layoutUpload', array('id' => $this->layoutId)); ?>" method="post" enctype="multipart/form-data">
    <input type="file" name="upload">
    <input type="submit" class="input-submit" value="<?php echo $this->escapeHtml($this->translate('Upload')); ?>">
</form>

<?php echo $this->partial('development/forms/layout.phtml', array('form' => $this->form)); ?>
<script type="text/javascript">
Gc.initCodeMirror('layout-content');
Gc.saveCommand();
</script>
