<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<table>
    <tr>
        <th><?php echo $this->escapeHtml($this->translate('Id')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Description')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Edit')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Delete')); ?></th>
    </tr>
    <?php foreach($this->layouts as $layout): ?>
        <tr>
            <td><?php echo $layout->getId(); ?></td>
            <td><?php echo $this->escapeHtml($layout->getName()); ?></td>
            <td><?php echo $this->escapeHtml($layout->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('layoutEdit', array('id' => $layout->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('layoutDelete', array('id' => $layout->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Delete')); ?>">
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

