<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php if ($this->acl('development', 'document-type')): ?>
    <h2>..:: <?php echo $this->escapeHtml($this->translate('Managing Document types')); ?> ::..</h2>

    <ul>
        <?php if ($this->acl('development', 'document-type/create')): ?>
            <li><a href="<?php echo $this->url('development/document-type/create'); ?>" title=""><?php echo $this->escapeHtml($this->translate('Add')); ?></a></li>
        <?php endif; ?>

        <?php if ($this->acl('development', 'document-type/list')): ?>
            <li><a href="<?php echo $this->url('development/document-type'); ?>" title=""><?php echo $this->escapeHtml($this->translate('List')); ?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>

<?php if ($this->acl('development', 'view')): ?>
    <h2>..:: <?php echo $this->escapeHtml($this->translate('Managing Views')); ?> ::..</h2>

    <ul>
        <?php if ($this->acl('development', 'view/create')): ?>
        <li><a href="<?php echo $this->url('development/view/create'); ?>" title=""><?php echo $this->escapeHtml($this->translate('Add')); ?></a></li>
        <?php endif; ?>

        <?php if ($this->acl('development', 'view/list')): ?>
            <li><a href="<?php echo $this->url('development/view'); ?>" title=""><?php echo $this->escapeHtml($this->translate('List')); ?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>

<?php if ($this->acl('development', 'layout')): ?>
    <h2>..:: <?php echo $this->escapeHtml($this->translate('Managing Layouts')); ?> ::..</h2>

    <ul>
        <?php if ($this->acl('development', 'layout/create')): ?>
        <li><a href="<?php echo $this->url('development/layout/create'); ?>" title=""><?php echo $this->escapeHtml($this->translate('Add')); ?></a></li>
        <?php endif; ?>

        <?php if ($this->acl('development', 'layout/list')): ?>
            <li><a href="<?php echo $this->url('development/layout'); ?>" title=""><?php echo $this->escapeHtml($this->translate('List')); ?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>

<?php if ($this->acl('development', 'script')): ?>
    <h2>..:: <?php echo $this->escapeHtml($this->translate('Managing Scripts')); ?> ::..</h2>

    <ul>
        <?php if ($this->acl('development', 'script/create')): ?>
        <li><a href="<?php echo $this->url('development/script/create'); ?>" title=""><?php echo $this->escapeHtml($this->translate('Add')); ?></a></li>
        <?php endif; ?>

        <?php if ($this->acl('development', 'script/list')): ?>
            <li><a href="<?php echo $this->url('development/script'); ?>" title=""><?php echo $this->escapeHtml($this->translate('List')); ?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>

<?php if ($this->acl('development', 'datatype')): ?>
    <h2>..:: <?php echo $this->escapeHtml($this->translate('Managing Datatypes')); ?> ::..</h2>

    <ul>
        <?php if ($this->acl('development', 'datatype/create')): ?>
        <li><a href="<?php echo $this->url('development/datatype/create'); ?>" title=""><?php echo $this->escapeHtml($this->translate('Add')); ?></a></li>
        <?php endif; ?>

        <?php if ($this->acl('development', 'datatype/list')): ?>
            <li><a href="<?php echo $this->url('development/datatype'); ?>" title=""><?php echo $this->escapeHtml($this->translate('List')); ?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
