<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>

<ul class="nav nav-list">
<?php if ($this->acl('development', 'document-type')): ?>
    <li>
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Document types')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <?php if ($this->acl('development', 'document-type/create')): ?>
                <li>
                    <a href="<?php echo $this->url('development/document-type/create'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('Create')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->acl('development', 'document-type/list')): ?>
                <li>
                    <a href="<?php echo $this->url('development/document-type'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('List')); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>
<?php endif; ?>

<?php if ($this->acl('development', 'view')): ?>
    <li>
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Views')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <?php if ($this->acl('development', 'view/create')): ?>
                <li>
                    <a href="<?php echo $this->url('development/view/create'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('Create')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->acl('development', 'view/list')): ?>
                <li>
                    <a href="<?php echo $this->url('development/view'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('List')); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>
<?php endif; ?>

<?php if ($this->acl('development', 'layout')): ?>
    <li>
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Layouts')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <?php if ($this->acl('development', 'layout/create')): ?>
                <li>
                    <a href="<?php echo $this->url('development/layout/create'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('Create')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->acl('development', 'layout/list')): ?>
                <li>
                    <a href="<?php echo $this->url('development/layout'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('List')); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>
<?php endif; ?>

<?php if ($this->acl('development', 'script')): ?>
    <li>
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Scripts')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <?php if ($this->acl('development', 'script/create')): ?>
                <li>
                    <a href="<?php echo $this->url('development/script/create'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('Create')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->acl('development', 'script/list')): ?>
                <li>
                    <a href="<?php echo $this->url('development/script'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('List')); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>
<?php endif; ?>

<?php if ($this->acl('development', 'datatype')): ?>
    <li>
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Datatypes')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <?php if ($this->acl('development', 'datatype/create')): ?>
                <li>
                    <a href="<?php echo $this->url('development/datatype/create'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('Create')); ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->acl('development', 'datatype/list')): ?>
                <li>
                    <a href="<?php echo $this->url('development/datatype'); ?>">
                        <i class="glyphicon glyphicon-arrow-right"></i>
                        <?php echo $this->escapeHtml($this->translate('List')); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </li>
<?php endif; ?>
</ul>
