<h2>..:: <?php echo $this->escape($this->translator('Managing Views')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('viewAdd'); ?>" title=""><?php echo $this->escape($this->translator('Add')); ?></a></li>
    <li><a href="<?php echo $this->url('viewList'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Managing Layouts')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('layoutAdd'); ?>" title=""><?php echo $this->escape($this->translator('Add')); ?></a></li>
    <li><a href="<?php echo $this->url('layoutList'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Managing Datatypes')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('datatypeAdd'); ?>" title=""><?php echo $this->escape($this->translator('Add')); ?></a></li>
    <li><a href="<?php echo $this->url('datatypeList'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Managing Document types')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url('documentTypeAdd'); ?>" title=""><?php echo $this->escape($this->translator('Add')); ?></a></li>
    <li><a href="<?php echo $this->url('documentTypeList'); ?>" title=""><?php echo $this->escape($this->translator('List')); ?></a></li>
</ul>
