<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Name')); ?></th>
        <th><?php echo $this->escape($this->translator('Description')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->layouts as $layout): ?>
        <tr>
            <td><?php echo $layout->getId(); ?></td>
            <td><?php echo $this->escape($layout->getName()); ?></td>
            <td><?php echo $this->escape($layout->getDescription()); ?></td>
            <td><a href="<?php echo $this->url('layoutEdit', array('id' => $layout->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('layoutDelete', array('id' => $layout->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>" />
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

