<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<h2>..:: <?php echo $this->escape($this->translator('Managing Users')); ?> ::..</h2>

<ul>
    <li><a href="" title=""><?php echo $this->escape($this->translator('Users list')); ?></a></li>
    <li><a href="" title=""><?php echo $this->escape($this->translator('Add')); ?></a></li>
</ul>

<h2>..:: <?php echo $this->escape($this->translator('Website Configuration')); ?> ::..</h2>

<ul>
    <li><a href="" title=""><?php echo $this->escape($this->translator('Managing Users')); ?></a></li>
    <li><a href="" title=""><?php echo $this->escape($this->translator('Managing Users')); ?></a></li>
</ul>
