<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
if(!empty($this->adminUser))
{
    $permissions = $this->adminUser->getRole()->getUserPermissions();
}
?>
<div class="part<?php if ($this->active == 'admin'): ?> active<?php endif; ?>">
    <a href="<?php echo $this->url('admin'); ?>">
        <img src="<?php echo $this->cdnBackend('backend/images/icones/accueil.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Dashboard')); ?>">
        <p>
            <?php echo $this->escapeHtml($this->translate('Dashboard')); ?><br>
            <?php echo $this->escapeHtml($this->translate('Administration Panel')); ?>
        </p>
    </a>
</div>

<?php if (!empty($permissions['Content'])): ?>
    <div class="part<?php if ($this->active == 'content'): ?> active<?php endif; ?>">
        <a href="<?php echo $this->url('content'); ?>">
            <img src="<?php echo $this->cdnBackend('backend/images/icones/content.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <p>
                <?php echo $this->escapeHtml($this->translate('Content')); ?><br>
                <?php echo $this->escapeHtml($this->translate('Manage content')); ?>
            </p>
        </a>
    </div>
<?php endif; ?>

<?php if (!empty($permissions['Development'])): ?>
    <div class="part<?php if ($this->active == 'development'): ?> active<?php endif; ?>">
        <a href="<?php echo $this->url('development'); ?>">
            <img src="<?php echo $this->cdnBackend('backend/images/icones/development.png'); ?>" width="35" height="40" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Development')); ?>">
            <p>
                <?php echo $this->escapeHtml($this->translate('Development')); ?><br>
                <?php echo $this->escapeHtml($this->translate('Manage documents')); ?>
            </p>
        </a>
    </div>
<?php endif; ?>

<?php if (!empty($permissions['Modules'])): ?>
    <div class="part<?php if ($this->active == 'module'): ?> active<?php endif; ?>">
        <a href="<?php echo $this->url('module'); ?>">
            <img src="<?php echo $this->cdnBackend('backend/images/icones/module.png'); ?>" width="35" height="39" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Development')); ?>">
            <p>
                <?php echo $this->escapeHtml($this->translate('Modules')); ?><br>
                <?php echo $this->escapeHtml($this->translate('Manage modules')); ?>
            </p>
        </a>
    </div>
<?php endif; ?>

<?php if (!empty($permissions['Stats'])): ?>
    <div class="part<?php if ($this->active == 'statistics'): ?> active<?php endif; ?>">
        <a href="<?php echo $this->url('statistics'); ?>">
            <img src="<?php echo $this->cdnBackend('backend/images/icones/stat.png'); ?>" width="32" height="32" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Stats')); ?>">
            <p>
                <?php echo $this->escapeHtml($this->translate('Stats')); ?><br>
                <?php echo $this->escapeHtml($this->translate('Website statistics')); ?>
            </p>
        </a>
    </div>
<?php endif; ?>

<?php if (!empty($permissions['Config'])): ?>
    <div class="part<?php if ($this->active == 'config'): ?> active<?php endif; ?>">
        <a href="<?php echo $this->url('config'); ?>">
            <img src="<?php echo $this->cdnBackend('backend/images/icones/config.png'); ?>" width="35" height="40" class="icone" alt="<?php echo $this->escapeHtml($this->translate('System')); ?>">
            <p>
                <?php echo $this->escapeHtml($this->translate('Configuration')); ?><br>
                <?php echo $this->escapeHtml($this->translate('System configuration')); ?>
            </p>
        </a>
    </div>
<?php endif; ?>

<?php if (!empty($this->adminUser)): ?>
    <div id="logout" class="part">
        <a href="<?php echo $this->url('config/user/logout'); ?>">
            <img src="<?php echo $this->cdnBackend('backend/images/icones/logout.png'); ?>" width="40" height="40" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Log out')); ?>">
            <p>
                <?php echo $this->escapeHtml(sprintf($this->translate('Welcome %s'), $this->adminUser->getName())); ?><br>
                <?php echo $this->escapeHtml($this->translate('Click to logout')); ?>
            </p>
        </a>
    </div>
<?php endif; ?>
