<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<div class="part">
    <a href=""><img src="<?php echo $this->basePath('images/icones/accueil.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Dashboard')); ?>"></a>
    <p><a href="<?php echo $this->url('admin'); ?>"><?php echo $this->escapeHtml($this->translate('Dashboard')); ?> <br /> Panneau d'administration</a></p>
</div>

<div class="part">
    <a href=""><img src="<?php echo $this->basePath('images/icones/blog.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Content')); ?>"></a>
    <p><a href="<?php echo $this->url('content'); ?>"><?php echo $this->escapeHtml($this->translate('Content')); ?> <br /> <?php echo $this->escapeHtml($this->translate('Manage content')); ?></a></p>
</div>

<div class="part">
    <a href=""><img src="<?php echo $this->basePath('images/icones/user.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Development')); ?>"></a>
    <p><a href="<?php echo $this->url('development'); ?>"><?php echo $this->escapeHtml($this->translate('Development')); ?> <br /> <?php echo $this->escapeHtml($this->translate('Manage documents')); ?></a></p>
</div>

<div class="part">
    <a href=""><img src="<?php echo $this->basePath('images/icones/stat.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('Stats')); ?>"></a>
    <p><a href="<?php echo $this->url('statistics'); ?>"><?php echo $this->escapeHtml($this->translate('Stats')); ?> <br /> <?php echo $this->escapeHtml($this->translate('Website statistics')); ?></a></p>
</div>

<div class="part">
    <a href=""><img src="<?php echo $this->basePath('images/icones/config.png'); ?>" width="36" height="36" class="icone" alt="<?php echo $this->escapeHtml($this->translate('System')); ?>"></a>
    <p><a href="<?php echo $this->url('config'); ?>"><?php echo $this->escapeHtml($this->translate('Configuration')); ?> <br /> <?php echo $this->escapeHtml($this->translate('System configuration')); ?></a></p>
</div>
