<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<form autocomplete="off" action="<?php echo $this->escapeHtml($this->form->getAttribute('action')); ?>" class="simple-form" method="post">
    <input type="image" src="<?php echo $this->basePath('backend/images/save.png'); ?>" value="1" alt="<?php echo $this->escapeHtml($this->translate('Save and publish')); ?>">
    <table id="table-translation-edit" class="table-list">
        <colgroup>
            <col width="43%">
            <col width="43%">
            <col width="14%">
        </colgroup>
        <thead>
            <tr>
                <th><?php echo $this->escapeHtml($this->translate('Source')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Destination')); ?></th>
                <th><?php echo $this->escapeHtml($this->translate('Locale')); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->values as $value): ?>
                <tr>
                    <td>
                        <div>
                            <?php echo $this->escapeHtml($value['source']); ?>
                        </div>

                        <div class="hide">
                            <input class="input-text" type="text" size="40" name="source[<?php echo $value['src_id']; ?>]" value="<?php echo $this->escapeHtml($value['source']); ?>">
                        </div>
                    </td>
                    <td>
                        <div>
                            <?php echo $this->escapeHtml($value['destination']); ?>
                        </div>

                        <div class="hide">
                            <input class="input-text" type="text" size="40" name="destination[<?php echo $value['src_id']; ?>][<?php echo $value['dst_id']; ?>][value]" value="<?php echo $this->escapeHtml($value['destination']); ?>">
                        </div>
                    </td>
                    <td>
                        <div>
                            <?php echo $this->escapeHtml($value['locale']); ?>
                        </div>

                        <div class="hide">
                            <select name="destination[<?php echo $value['src_id']; ?>][<?php echo $value['dst_id']; ?>][locale]">
                                <?php foreach($this->form->get('locale')->getValueOptions() as $option_id => $option_value): ?>
                                    <option value="<?php echo $option_id; ?>"><?php echo $this->escapeHtml($option_value); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <input type="hidden" name="destination[<?php echo $value['src_id']; ?>][<?php echo $value['dst_id']; ?>][dst_id]" value="<?php echo $value['dst_id']; ?>">
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</form>

<script type="text/javascript">
$(document).ready(function(){
    Gc.setOption('locale', $.parseJSON('<?php echo $this->json($this->form->get('locale')->getValueOptions()); ?>'));
    Gc.initTraslationList();
});
</script>
