<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<ul>
    <li><a href="#tabs-1"><?php echo $this->escape($this->translator('Infos')); ?></a></li>
    <li><a href="#tabs-2"><?php echo $this->escape($this->translator('Views')); ?></a></li>
    <li><a href="#tabs-3"><?php echo $this->escape($this->translator('Properties')); ?></a></li>
    <li><a href="#tabs-4"><?php echo $this->escape($this->translator('Tabs')); ?></a></li>
</ul>
<?php $infos_form = $this->element->infos; ?>
<?php $views_form = $this->element->views; ?>
<?php $tabs_form = $this->element->tabs->getSubForms(); ?>
<?php $properties_forms = $this->element->properties->getSubForms(); ?>
<form id="development-form" enctype="application/x-www-form-urlencoded" action="<?php echo $this->element->getAction(); ?>" method="post">
    <dl id="tabs-1">
        <dt id="name-label">
            <label for="infos-name" class="optional"><?php echo $this->escape($this->translator('Name')); ?></label>
        </dt>
        <dd id="name-element">
            <input type="text" name="infos[name]" id="infos-name" value="<?php echo $infos_form->getValue('name'); ?>">
        </dd>
        <dt id="description-label">
            <label for="infos-description" class="optional"><?php echo $this->escape($this->translator('Description')); ?></label>
        </dt>
        <dd id="description-element">
            <input type="text" name="infos[description]" id="infos-description" value="<?php echo $infos_form->getValue('description'); ?>">
        </dd>
        <dt id="icon_id-label">
            <label for="infos-icon_id" class="optional"><?php echo $this->escape($this->translator('Icon')); ?></label>
        </dt>
        <dd id="icon_id-element">
            <select name="infos[icon_id]" id="infos-icon_id">

            </select>
        </dd>
    </dl>

    <dl id="tabs-2">
        <dt id="default_view_id-label">
            <label for="views-default_view_id" class="required"><?php echo $this->escape($this->translator('Default view')); ?></label>
        </dt>

        <dd id="default_view_id-element">
            <select name="views[default_view]" id="views-default_view">
                <option value=""><?php echo $this->escape($this->translator('-- Select --')); ?></option>
                <?php foreach($views as $view_id => $view_name): ?>
                    <option value="<?php echo $view_id; ?>"<?php if($views_form->getValue('default_view') == $view_id): ?> selected="selected"<?php endif; ?>><?php echo $this->escape($view_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt id="all_views-label">
            <label for="views-all_views" class="optional"><?php echo $this->escape($this->translator('Add view')); ?></label>
        </dt>
        <dd id="all_views-element">
            <select name="views[available_views]" id="views-available_views" multiple="multiple">
                <?php foreach($views as $view_id => $view_name): ?>
                    <option value="<?php echo $view_id; ?>"><?php echo $this->escape($view_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt id="add-label">&nbsp;</dt>
        <dd id="add-element">
            <button name="views[add]" id="views-add" type="button" class="button-add button-add-view"><?php echo $this->escape($this->translator('Add view')); ?></button>
        </dd>
    </dl>

    <dl id="tabs-3">
        <dt id="name-label">
            <label for="properties-name" class="optional"><?php echo $this->escape($this->translator('Name')); ?></label>
        </dt>
        <dd id="name-element">
            <input type="text" name="properties[name]" id="properties-name" value="">
        </dd>
        <dt id="identifier-label">
            <label for="properties-identifier" class="optional"><?php echo $this->escape($this->translator('Identifier')); ?></label>

        </dt>
        <dd id="identifier-element">
            <input type="text" name="properties[identifier]" id="properties-identifier" value="">
        </dd>
        <dt id="tab-label">
            <label for="properties-tab" class="required"><?php echo $this->escape($this->translator('Tab')); ?></label>
        </dt>
        <dd id="tab-element">
            <select name="properties[tab]" id="properties-tab" class="select-tab">
                <option value="" label="-- Select tab --" selected="selected">-- Select tab --</option>
                <?php foreach($tabs_form as $form): ?>
                    <option value="<?php echo $form->getValue('tab_id'); ?>"><?php echo $form->getValue('name'); ?></option>
                <?php endforeach; ?>
            </select>
        </dd>

        <dt id="datatype-label">
            <label for="properties-datatype" class="required"><?php echo $this->escape($this->translator('Datatype')); ?></label>
        </dt>
        <dd id="datatype-element">
            <select name="properties[datatype]" id="properties-datatype" class="select-datatype">
                <option value=""><?php echo $this->escape($this->translator('-- Select --')); ?></option>
                <?php foreach($datatypes as $datatype_id => $datatype_name): ?>
                    <option value="<?php echo $datatype_id; ?>"><?php echo $this->escape($datatype_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt id="description-label">
            <label for="properties-description" class="optional"><?php echo $this->escape($this->translator('Description')); ?></label>
        </dt>
        <dd id="description-element">
            <input type="text" name="properties[description]" id="properties-description" value="">
        </dd>
        <dt id="required-label">
            <label for="properties-required" class="optional"><?php echo $this->escape($this->translator('Required')); ?></label>
        </dt>

        <dd id="required-element">
            <input type="checkbox" name="properties[required]" id="properties-required" value="1">
        </dd>
        <dt id="add-label">&nbsp;</dt>
        <dd id="add-element">
            <button name="properties[add]" id="property_add" type="button" class="button-add button-add-property"><?php echo $this->escape($this->translator('Add property')); ?></button>
        </dd>
        <dt><?php echo $this->escape($this->translator('Properties')); ?></dt>
        <dd>
            <div id="properties-tabs-content" class="tabs">
                <ul>
                    <?php foreach($tabs_form as $form): ?>
                        <li>
                            <?php $name = $form->getValue('name'); ?>
                            <a href="#tabs-properties-<?php echo $form->getValue('tab_id'); ?>">
                                <?php echo $name; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <?php foreach($tabs_form as $form): ?>
                    <div id="tabs-properties-<?php echo $form->getValue('tab_id'); ?>">
                        <ul>
                            <?php foreach($properties_forms as $property): ?>
                                <?php if($property->getValue('tab') != $form->getValue('tab_id')): ?>
                                    <?php continue; ?>
                                <?php endif; ?>
                                <?php $property_id = 'property'.$property->getValue('property_id'); ?>

                                <dl>
                                    <dt>
                                        <label class="optional" for="properties-name-<?php echo (int)$property->getValue('property_id'); ?>"><?php echo $this->escape($this->translator('Name')); ?></label>
                                    </dt>
                                    <dd>
                                        <input type="text" value="<?php echo $this->escape($property->getValue('name')); ?>" id="properties-name-<?php echo (int)$property->getValue('property_id'); ?>" name="properties[<?php echo $property_id; ?>][name]">
                                    </dd>
                                    <dt>
                                        <label class="optional" for="properties-identifier-<?php echo (int)$property->getValue('property_id'); ?>"><?php echo $this->escape($this->translator('Identifier')); ?></label>
                                    </dt>
                                    <dd>
                                        <input type="text" value="<?php echo $this->escape($property->getValue('identifier')); ?>" id="properties-identifier-<?php echo (int)$property->getValue('property_id'); ?>" name="properties[<?php echo $property_id; ?>][identifier]">
                                    </dd>
                                    <dt>
                                        <label class="optional" for="properties-datatype-<?php echo (int)$property->getValue('property_id'); ?>"><?php echo $this->escape($this->translator('Datatype')); ?></label>
                                    </dt>
                                    <dd>
                                        <select class="select-datatype" id="properties-datatype-<?php echo (int)$property->getValue('property_id'); ?>" name="properties[<?php echo $property_id; ?>][datatype]">
                                            <option value=""><?php echo $this->escape($this->translator('-- Select --')); ?></option>
                                            <?php foreach($datatypes as $datatype_id => $datatype_name): ?>
                                                <option value="<?php echo $datatype_id; ?>"<?php if($datatype_id == $property->getValue('datatype')): ?> selected="selected"<?php endif; ?>><?php echo $this->escape($datatype_name); ?> </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </dd>
                                    <dt>
                                        <label class="optional" for="properties-description-<?php echo (int)$property->getValue('property_id'); ?>"><?php echo $this->escape($this->translator('Description')); ?></label>
                                    </dt>
                                    <dd>
                                        <input type="text" value="<?php echo $this->escape($property->getValue('description')); ?>" id="properties-description-<?php echo (int)$property->getValue('property_id'); ?>" name="properties[<?php echo $property_id; ?>][description]">
                                    </dd>
                                    <dt>
                                        <label class="optional" for="properties-required-<?php echo (int)$property->getValue('property_id'); ?>"><?php echo $this->escape($this->translator('Required')); ?></label>
                                    </dt>
                                    <dd>
                                        <input type="checkbox" value="<?php echo $property->getValue('required'); ?>" id="properties-required-<?php echo (int)$property->getValue('property_id'); ?>" name="properties[<?php echo $property_id; ?>][required]">
                                    </dd>
                                    <dd>
                                        <input type="hidden" id="properties-tab-<?php echo (int)$property->getValue('property_id'); ?>" name="properties[<?php echo $property_id; ?>][tab]" value="<?php echo (int)$property->getValue('tab'); ?>">
                                        <button type="button" value="<?php echo (int)$property->getValue('property_id'); ?>" class="delete-property"><?php echo $this->escape($this->translator('Delete')); ?></button>
                                    </dd>
                                </dl>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endforeach; ?>
            </div>
        </dd>
    </dl>

    <dl id="tabs-4">
        <dt id="addname-label">
            <label for="tabs-addname" class="optional"><?php echo $this->escape($this->translator('Name')); ?></label>
        </dt>
        <dd id="addname-element">
            <input type="text" name="tabs[addname]" id="tabs-addname" value="">
        </dd>
        <dt id="adddescription-label">
            <label for="tabs-adddescription" class="optional"><?php echo $this->escape($this->translator('Description')); ?></label>
        </dt>
        <dd id="adddescription-element">
            <input type="text" name="tabs[adddescription]" id="tabs-adddescription" value="">
        </dd>
        <dt id="add-label">&nbsp;</dt>
        <dd id="add-element">
            <button name="tabs[add]" id="tabs-add" type="button" class="button-add button-add-tab"><?php echo $this->escape($this->translator('Add Tab')); ?></button>
        </dd>

        <dt><?php echo $this->escape($this->translator('Tabs')); ?></dt>
        <dd>
            <ul id="tabs" class="sortable ui-sortable">
            <?php foreach($tabs_form as $form): ?>
                <li>
                    <?php $name = $form->getValue('name'); ?>
                    <?php $description = $form->getValue('description'); ?>
                    <?php $tab_id = 'tab'.$form->getValue('tab_id'); ?>
                    <input type="hidden" value="<?php echo $name; ?>" name="tabs[<?php echo $tab_id; ?>][name]">
                    <input type="hidden" value="<?php echo $description; ?>" name="tabs[<?php echo $tab_id; ?>][description]">
                    <span><?php echo $name; ?></span>
                    <span><?php echo $description; ?></span>
                    <button value="<?php echo (int)$form->getValue('tab_id'); ?>" class="delete-tab" type="button">delete</button>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
    </dl>

    <div>
        <input type="submit" name="submit" id="submit" value="Submit">
    </div>
</form>
