<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Config
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>

<div class="one-page-box visible widget-box no-border col-xs-12">
    <div class="widget-body">
        <div class="widget-main">
            <h4 class="header">
                <?php echo $this->escapeHtml($this->translate('Forgot your password?')); ?>
            </h4>

            <form id="one-page-form" action="<?php echo $this->form->getAttribute('action'); ?>" method="post">
                <fieldset class="has-warning">
                    <?php if ($this->form->has('email')): ?>
                        <span class="block input-glyphicon input-glyphicon-right">
                            <input type="email" name="email" class="form-control" placeholder="<?php echo $this->escapeHtml($this->translate('Email')); ?>" />
                            <i class="glyphicon glyphicon-envelope"></i>
                        </span>
                    <?php else: ?>
                        <span class="block input-glyphicon input-glyphicon-right">
                            <input name="password" id="password" type="password" class="form-control" placeholder="<?php echo $this->escapeHtml($this->translate('Password')); ?>" required>
                            <i class="icon-envelope"></i>
                        </span>
                        <span class="block input-glyphicon input-glyphicon-right">
                            <input name="password_confirm" id="password-confirm" type="password" class="form-control" placeholder="<?php echo $this->escapeHtml($this->translate('Confirm password')); ?>" required>
                            <i class="icon-envelope"></i>
                        </span>
                    <?php endif; ?>

                    <div class="clearfix buttons">
                        <button class="pull-right btn btn-small btn-warning">
                            <i class="glyphicon glyphicon-log-in"></i>
                            <?php echo $this->escapeHtml($this->translate('Check')); ?>
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>

        <div class="footer clearfix text-right">
            <a href="<?php echo $this->url('config/user/login'); ?>">
                <i class="glyphicon glyphicon-log-in"></i>
                <?php echo $this->escapeHtml($this->translate('Back to login')); ?>
            </a>
        </div>
    </div>
</div>
