<table>
    <tr>
        <th><?php echo $this->escapeHtml($this->translate('Id')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Lastname')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Firstname')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Email')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Login')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Edit')); ?></th>
        <th><?php echo $this->escapeHtml($this->translate('Delete')); ?></th>
    </tr>
    <?php foreach($this->users as $user): ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $this->escapeHtml($user->getLastname()); ?></td>
            <td><?php echo $this->escapeHtml($user->getFirstname()); ?></td>
            <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
            <td><?php echo $this->escapeHtml($user->getLogin()); ?></td>
            <td><a href="<?php echo $this->url('userEdit', array('id' => $user->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('userDelete', array('id' => $user->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Delete')); ?>">
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>

