<form id="one-page-form" action="<?php echo $this->url('userLogin'); ?>" method="post">
    <h1><?php echo $this->escapeHtml($this->translate('Log In')); ?></h1>
    <fieldset id="inputs">
        <input name="login" id="login" type="text" placeholder="<?php echo $this->escapeHtml($this->translate('Login')); ?>" autofocus required>
        <input name="password" id="password" type="password" placeholder="<?php echo $this->escapeHtml($this->translate('Password')); ?>" required>
        <input name="redirect" id="redirect" type="hidden" value="<?php echo $this->escapeHtml($this->form->get('redirect')->getValue()); ?>">
    </fieldset>
    <fieldset id="actions">
        <input type="submit" id="submit" value="<?php echo $this->escapeHtml($this->translate('Log In')); ?>">
        <a href="<?php echo $this->url('userForgotPassword'); ?>"><?php echo $this->escapeHtml($this->translate('Forgot your password?')); ?></a>
    </fieldset>
</form>
