<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
    <?php
    echo $this->headTitle();
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript();

    echo $this->HeadLink();
    ?>
</head>
<body>
    <header class="gradient-black">
        <?php echo $this->partial('navigation.phtml', array('active' => $this->module, 'adminUser' => $this->adminUser)); ?>
    </header>

    <div id="main">

        <?php if($this->module !== NULL): ?>
            <div id="menu">
                <?php echo $this->partial($this->module . '-menu.phtml', array('treeview' => $this->treeview)); ?>
            </div>
        <?php endif; ?>

        <div id="content">
            <?php echo $this->partial('messages.phtml', array('messages' => $this->flashMessages)); ?>
            <?php echo $this->content; ?>
        </div>

        <div style="clear:both;"></div>
    </div>

    <footer>
        © 2012 <a href="">GotCms</a>
    </footer>

    <script type="text/javascript">
        <?php if(!empty($this->routes)): ?>
            $(document).ready(function()
            {
                Gc.setOption('routes', $.parseJSON('<?php echo $this->escapeJs($this->routes); ?>'));
                Gc.initDocumentMenu(<?php echo $this->documentId; ?>);
            });
        <?php endif; ?>
    </script>

    <div id="dialog" title="">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">&nbsp;</span>
            <?php echo $this->escapeHtml($this->translate('These items will be permanently deleted and cannot be recovered. Are you sure?')); ?>
        </p>
    </div>
</body>
</html>
