<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
    <?php
    echo $this->headTitle();
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript();

    echo $this->HeadLink();
    ?>
</head>
<body>
    <header>
        <div id="logo"></div>
        <div id="connexion">
            <ul>
                <li><?php echo $this->escapeHtml(sprintf($this->translate('Welcome %s'), $this->adminName)); ?> - <a href="#">MP (0/6)</a></li>
                <li><a href="#">Voir les derniers signalements</a></li>
                <li><a href="<?php echo $this->url('userLogout'); ?>">[ <?php echo $this->escapeHtml($this->translate('Disconnect')); ?> ]</a></li>
            </ul>
        </div>
    </header>

    <div id="navigation">
        <?php echo $this->partial('navigation.phtml', 'default', 'test'); ?>
    </div>

    <div id="main-top"></div>
    <div id="main">

        <div id="menu">
            <?php if($this->module !== NULL): ?>
                <?php echo $this->partial($this->module . '-menu.phtml', array('treeview' => $this->treeview)); ?>
            <?php endif; ?>
        </div>

        <div id="content">
            <?php echo $this->content; ?>
        </div>

        <div style="clear:both;"></div>
    </div>

    <footer>
        © 2012 <a href="">GotCms</a>
    </footer>

    <script type="text/javascript">
        <?php if(!empty($this->routes)): ?>
            $(document).ready(function()
            {
                Gc.setOption('routes', $.parseJSON('<?php echo $this->escapeJs($this->routes); ?>'));
                Gc.initDocumentMenu(<?php echo $this->documentId; ?>);
            });
        <?php endif; ?>
    </script>

    <?php if($this->treeview): ?>
        <ul id="contextMenu" class="contextMenu">
            <li class="new"><a href="#new"><?php echo $this->escapeHtml($this->translate('New')); ?></a></li>
            <li class="edit"><a href="#edit"><?php echo $this->escapeHtml($this->translate('Edit')); ?></a></li>
            <li class="cut separator"><a href="#cut"><?php echo $this->escapeHtml($this->translate('Cut')); ?></a></li>
            <li class="copy"><a href="#copy"><?php echo $this->escapeHtml($this->translate('Copy')); ?></a></li>
            <li class="paste"><a href="#paste"><?php echo $this->escapeHtml($this->translate('Paste')); ?></a></li>
            <li class="delete"><a href="#delete"><?php echo $this->escapeHtml($this->translate('Delete')); ?></a></li>
            <li class="quit separator"><a href="#quit"><?php echo $this->escapeHtml($this->translate('Quit')); ?></a></li>
        </ul>
    <?php endif; ?>

    <div id="dialog" title="" style="display:none">
        <p>
            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">&nbsp;</span>
            <?php echo $this->escapeHtml($this->translate('These items will be permanently deleted and cannot be recovered. Are you sure?')); ?>
        </p>
    </div>
</body>
</html>
