<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/GPL http://www.gnu.org/licenses/gpl-3.0.html
 * @link     http://www.got-cms.com
 * @license  http://www.gnu.org/licenses/gpl-3.0.html
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
    <?php
    echo $this->headTitle();
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript()
        ->appendFile('/js/libs/modernizr-2.5.3.min.js', 'text/javascript')
        ->appendFile('/js/libs/jquery-1.7.2.min.js', 'text/javascript')
        ->appendFile('/js/plugins.js', 'text/javascript')
        ->appendFile('/js/libs/jquery-ui-1.8.14.js', 'text/javascript')
        ->appendFile('/js/gotcms.js', 'text/javascript');

    echo $this->HeadLink()
        ->appendStylesheet('/css/style.css');
    ?>
</head>
<body>
    <?php echo $this->content; ?>
</body>
</html>
