<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
    <?php
    echo $this->headTitle();
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript()
        ->appendFile('/js/libs/modernizr-2.5.3.min.js', 'text/javascript')
        ->appendFile('/js/libs/jquery-1.7.2.min.js', 'text/javascript')
        ->appendFile('/js/plugins.js', 'text/javascript')
        ->appendFile('/js/libs/jquery-ui-1.8.14.js', 'text/javascript')
        ->appendFile('/js/gotcms.js', 'text/javascript');

    echo $this->HeadLink()
        ->appendStylesheet('/css/style.css');
    ?>
</head>
<body>
    <?php echo $this->content; ?>
</body>
</html>
