<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Application
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<div class="page-header position-relative">
    <h1>
        <?php echo $this->escapeHtml(sprintf($this->translate('Pre-installation check for GotCms %s'), $this->cmsVersion)); ?>
    </h1>
</div>

<p><?php echo $this->escapeHtml($this->translate('Please make sure all parameters are set to "Yes" before continue installation')); ?></p>

<div class="install-body">
    <fieldset>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th><?php echo $this->escapeHtml($this->translate('Directive')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Status')); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->phpData as $data): ?>
                    <tr>
                        <td>
                            <?php echo $this->escapeHtml($this->translate($data['label'])); ?>
                        </td>
                        <?php if ($data['value'] === true): ?>
                            <td class="success">
                                <span>
                                    <?php echo $this->escapeHtml($this->translate('Yes')); ?>
                                </span>
                            </td>
                        <?php else: ?>
                            <td class="error">
                                <span>
                                    <?php echo $this->escapeHtml($this->translate('No')); ?>
                                </span>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>

                <?php if (!empty($this->gitProject)): ?>
                    <tr>
                        <td>
                            <?php echo $this->escapeHtml($this->translate('Git project has been found, make sure you clone with apache user.')); ?>
                        </td>
                        <td class="warning">
                            <span>
                                <?php echo $this->escapeHtml($this->translate('Care')); ?>
                            </span>
                        </td>
                    </tr>
                <?php endif; ?>

                <?php foreach ($this->serverData as $data): ?>
                    <tr>
                        <td>
                            <?php echo $this->escapeHtml(sprintf($this->translate('%s is writable'), $data['label'])); ?>
                        </td>
                        <?php if ($data['value'] === true): ?>
                            <td class="success">
                                <span>
                                    <?php echo $this->escapeHtml($this->translate('Yes')); ?>
                                </span>
                            </td>
                        <?php else: ?>
                            <td class="error">
                                <span>
                                    <?php echo $this->escapeHtml($this->translate('No')); ?>
                                </span>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>
</div>

<h3><?php echo $this->escapeHtml($this->translate('Recommended settings:')); ?></h3>
<p>
    <?php echo $this->escapeHtml($this->translate('These settings are recommended for PHP in order to ensure full compatibility.')); ?>
</p>
<div class="install-body">
    <fieldset>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>
                    <?php echo $this->escapeHtml($this->translate('Directive')); ?>
                </th>
                <th>
                    <?php echo $this->escapeHtml($this->translate('Recommended')); ?>
                </th>
                <th>
                    <?php echo $this->escapeHtml($this->translate('Actual')); ?>
                </th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->phpDirective as $data): ?>
                    <tr>
                        <td>
                            <?php echo $this->escapeHtml($this->translate($data['label'])); ?>
                        </td>

                        <td class="toggle">
                            <span>
                                <?php echo $this->escapeHtml($this->translate($data['needed'] === true ? 'On' : 'Off')); ?>
                            </span>
                        </td>
                        <td class="<?php if ($data['needed'] === $data['value']): ?>success<?php else: ?>warning<?php endif; ?>">
                            <span>
                                <?php echo $this->escapeHtml($this->translate($data['value'] === true ? 'On' : 'Off')); ?>
                            </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>
</div>
<div class="clr"></div>
