<table>
	<tr>
		<th><?php echo $this->escape($this->translate('Id')); ?></th>
		<th><?php echo $this->escape($this->translate('Name')); ?></th>
		<th><?php echo $this->escape($this->translate('Model')); ?></th>
		<th><?php echo $this->escape($this->translate('Edit')); ?></th>
		<th><?php echo $this->escape($this->translate('Delete')); ?></th>
	</tr>
	<?php foreach($this->datatypes as $datatype): ?>
		<tr>
			<td><?php echo $datatype->getId(); ?></td>
			<td><?php echo $this->escape($datatype->getName()); ?></td>
			<td><?php echo $this->escape($datatype->getModel()->getName()); ?></td>
			<td><a href="<?php echo $this->url(array('id' => $datatype->getId()), 'datatypeEdit'); ?>">img edit</a></td>
			<td><a href="<?php echo $this->url(array('id' => $datatype->getId()), 'datatypeDelete'); ?>">img delete</a></td>
		</tr>
	<?php endforeach; ?>
</table>
