<form id="one-page-form" action="<?php echo $this->url('userForgotPassword'); ?>" method="post">
    <h1 class="forgot-password"><?php echo $this->escape($this->translator('Forgot password?')); ?></h1>
    <fieldset id="inputs">
        <input name="email" id="login" type="email" placeholder="<?php echo $this->escape($this->translator('Email')); ?>" autofocus required>
    </fieldset>
    <fieldset id="actions">
        <input type="submit" id="submit" value="Log in">
    </fieldset>
</form>
