<form id="one-page-form" action="<?php echo $this->url('userLogin'); ?>" method="post">
    <h1><?php echo $this->escape($this->translator('Log In')); ?></h1>
    <fieldset id="inputs">
        <input name="login" id="login" type="text" placeholder="<?php echo $this->escape($this->translator('Login')); ?>" autofocus required>
        <input name="password" id="password" type="password" placeholder="<?php echo $this->escape($this->translator('Password')); ?>" required>
    </fieldset>
    <fieldset id="actions">
        <input type="submit" id="submit" value="Log in">
        <a href="<?php echo $this->url('userForgotPassword'); ?>"><?php echo $this->escape($this->translator('Forgot your password?')); ?></a>
    </fieldset>
</form>
