<h2>..:: <?php echo $this->escape($this->translate('Managing documents')); ?> ::..</h2>

<ul>
    <li><a href="<?php echo $this->url(array(), 'documentAdd'); ?>" title=""><?php echo $this->escape($this->translate('Add')); ?></a></li>
    <li><a href="<?php echo $this->url(array(), 'documentList'); ?>" title=""><?php echo $this->escape($this->translate('List')); ?></a></li>
</ul>

<ul id="browser" class="filetree">
    <li><span class="folder">Folder 1</span>
        <ul>
            <li><span class="file">Item 1.1</span></li>
        </ul>
    </li>
    <li><span class="folder">Folder 2</span>
        <ul>
            <li><span class="folder">Subfolder 2.1</span>
                <ul id="folder21">
                    <li><span class="file">File 2.1.1</span></li>
                    <li><span class="file">File 2.1.2</span></li>
                </ul>
            </li>
            <li><span class="file">File 2.2</span></li>
        </ul>
    </li>
    <li class="closed"><span class="folder">Folder 3 (closed at start)</span>
        <ul>
            <li><span class="file">File 3.1</span></li>
        </ul>
    </li>
    <li><span class="file">File 4</span></li>
</ul>
