<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Config
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>

<div class="one-page-box visible widget-box no-border col-xs-12">
    <div class="widget-body">
        <div class="widget-main">
            <h4 class="header">
                <?php echo $this->escapeHtml($this->translate('Log In')); ?>
            </h4>

            <form id="one-page-form" action="<?php echo $this->url('config/user/login'); ?>" method="post">
                <fieldset class="has-warning">
                    <span class="block input-glyphicon input-glyphicon-right">
                        <input name="login" type="text" class="form-control" placeholder="<?php echo $this->escapeHtml($this->translate('Login')); ?>" autofocus required />
                        <i class="glyphicon glyphicon-user"></i>
                    </span>

                    <span class="block input-glyphicon input-glyphicon-right">
                        <input name="password" type="password" class="form-control" placeholder="<?php echo $this->escapeHtml($this->translate('Password')); ?>" required />
                        <i class="glyphicon glyphicon-lock"></i>
                    </span>

                    <div class="clearfix buttons">
                        <input name="redirect" id="redirect" type="hidden" value="<?php echo $this->escapeHtml($this->form->get('redirect')->getValue()); ?>">

                        <button class="pull-right btn btn-small btn-warning">
                            <i class="glyphicon glyphicon-log-in"></i>
                            <?php echo $this->escapeHtml($this->translate('Log In')); ?>
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>

        <div class="footer clearfix text-right">
            <a href="<?php echo $this->url('config/user/forgot-password'); ?>">
                <i class="glyphicon glyphicon-exclamation-sign"></i>
                <?php echo $this->escapeHtml($this->translate('Forgot your password?')); ?>
            </a>
        </div>
    </div>
</div>
