<?php echo $this->doctype('XHTML1_STRICT').PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <?php
    echo $this->headTitle();
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
    echo $this->headScript()
        ->appendFile('/js/prototype.js', 'text/javascript')
        ->appendFile('/js/jquery-1.7.1.min.js', 'text/javascript')
        ->appendFile('/js/jquery-ui-1.8.14.js', 'text/javascript')
        ->appendFile('/js/translate.js', 'text/javascript')
        ->appendFile('/js/validate.js', 'text/javascript')
        ->appendFile('/js/form.js', 'text/javascript')
        ->appendFile('/js/codemirror/lib/codemirror.js', 'text/javascript')
        ->appendFile('/js/codemirror/mode/xml/xml.js', 'text/javascript')
        ->appendFile('/js/codemirror/mode/javascript/javascript.js', 'text/javascript')
        ->appendFile('/js/codemirror/mode/css/css.js', 'text/javascript')
        ->appendFile('/js/codemirror/mode/clike/clike.js', 'text/javascript')
        ->appendFile('/js/codemirror/mode/php/php.js', 'text/javascript')
        ->appendFile('/js/jquery.treeview.js', 'text/javascript')
        ->appendFile('/js/jquery.contextMenu.js', 'text/javascript')
        ->appendFile('/js/escms.js', 'text/javascript').PHP_EOL;

    echo $this->HeadLink()
        ->appendStylesheet('/css/style.css')
        ->appendStylesheet('/js/codemirror/lib/codemirror.css')
        ->appendStylesheet('/js/codemirror/mode/xml/xml.css')
        ->appendStylesheet('/js/codemirror/mode/javascript/javascript.css')
        ->appendStylesheet('/js/codemirror/mode/css/css.css')
        ->appendStylesheet('/js/codemirror/mode/clike/clike.css')
        ->appendStylesheet('/css/jquery-ui-1.8.14.custom.css')
        ->appendStylesheet('/css/jquery.treeview.css')
        ->appendStylesheet('/css/jquery.contextMenu.css');
    ?>
</head>
<body>
    <div id="header">
        <div id="logo"></div>
        <div id="connexion">
            <table width="316" border="0">
                <tr>
                    <td colspan="2" rowspan="3" align="center" valign="middle">&nbsp;</td>
                    <td width="10">&nbsp;</td>
                    <td width="227" height="22">Bienvenue “Admin” - <a href="#">MP (0/6)</a></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td height="19"><a href="#">Voir les derniers signalements</a></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><a href="#">[ Deconnexion ]</a></td>
                </tr>
            </table>
        </div>
    </div>

    <div id="navigation">
        <?php echo $this->partial('navigation.phtml', 'default'); ?>
    </div>

    <div id="main-top"></div>
    <div id="main">

        <div id="menu">
            <?php echo $this->partial('menu.phtml', array('treeview' => $this->layout()->treeview)); ?>
        </div>

        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>

        <div style="clear:both;"></div>
    </div>

    <div id="footer">
        © 2011 <a href="">EsCMS</a>
    </div>

    <?php if($this->layout()->treeview): ?>
        <script type="text/javascript">
            jQuery(document).ready(function()
            {
                ES.getInstance().initDocumentMenu();
            });
        </script>

        <ul id="contextMenu" class="contextMenu">
            <li class="new"><a href="#new"><?php echo $this->escape($this->translate('New')); ?></a></li>
            <li class="edit"><a href="#edit"><?php echo $this->escape($this->translate('Edit')); ?></a></li>
            <li class="cut separator"><a href="#cut"><?php echo $this->escape($this->translate('Cut')); ?></a></li>
            <li class="copy"><a href="#copy"><?php echo $this->escape($this->translate('Copy')); ?></a></li>
            <li class="paste"><a href="#paste"><?php echo $this->escape($this->translate('Paste')); ?></a></li>
            <li class="delete"><a href="#delete"><?php echo $this->escape($this->translate('Delete')); ?></a></li>
            <li class="quit separator"><a href="#quit"><?php echo $this->escape($this->translate('Quit')); ?></a></li>
        </ul>
    <?php endif; ?>
</body>
</html>
