<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>
<h1><?php echo $this->escapeHtml($this->translate('Statistics')); ?></h1>

<div class="tabs">
    <ul>
        <?php foreach($this->groups as $type => $data): ?>
            <li><a href="#<?php echo $this->escapeHtml($type); ?>"><?php echo $this->escapeHtml($data['label']); ?></a></li>
        <?php endforeach; ?>
    </ul>

    <?php foreach($this->groups as $type => $data): ?>
        <?php $values = $data['values']; ?>
        <?php $labels = $data['labels']; ?>
        <div id="<?php echo $this->escapeHtml($type); ?>">
            <div class="floatL">
                <?php if(!empty($values['pagesviews'])): ?>
                    <h2><?php echo $this->escapeHtml($this->translate($labels['pagesviews'])); ?></h2>
                    <?php $this->graph->Values($values['pagesviews']); ?>
                    <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
                    <?php echo $this->graph->FetchJavascript(); ?>
                <?php endif; ?>
            </div>

            <div class="floatL">
                <?php if(!empty($values['visitors'])): ?>
                    <h2><?php echo $this->escapeHtml($this->translate($labels['visitors'])); ?></h2>
                    <?php $this->graph->Values($values['visitors']); ?>
                    <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
                    <?php echo $this->graph->FetchJavascript(); ?>
                <?php endif; ?>
            </div>

            <div class="cb">
                <?php if(!empty($values['urlsviews'])): ?>
                    <h2><?php echo $this->escapeHtml($this->translate($labels['urlsviews'])); ?></h2>
                    <ul>
                        <?php foreach($values['urlsviews'] as $value): ?>
                            <li>
                                <span class="floatL"><?php echo $this->escapeHtml($value['url']); ?></span>
                                <span class="floatR"><?php echo $this->escapeHtml($value['nb']); ?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>

        </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    $('.tabs').tabs();
</script>
