<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>
<h1><?php echo $this->escapeHtml($this->translate('Statistics')); ?></h1>

<div class="floatL">
    <?php if(!empty($this->visistsHours)): ?>
        <h2><?php echo $this->escapeHtml($this->translate('Visits today')); ?></h2>
        <?php $this->graph->Values($this->visistsHours); ?>
        <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
        <?php echo $this->graph->FetchJavascript(); ?>
    <?php endif; ?>

    <?php if(!empty($this->visistsDays)): ?>
        <h2><?php echo $this->escapeHtml($this->translate('Visits this month')); ?></h2>
        <?php $this->graph->Values($this->visistsDays); ?>
        <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
        <?php echo $this->graph->FetchJavascript(); ?>
    <?php endif; ?>

    <?php if(!empty($this->visistsMonths)): ?>
        <h2><?php echo $this->escapeHtml($this->translate('Visits this year')); ?></h2>
        <?php $this->graph->Values($this->visistsMonths); ?>
        <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
        <?php echo $this->graph->FetchJavascript(); ?>
    <?php endif; ?>
</div>
<div class="floatR">
    <?php if(!empty($this->visistorsHours)): ?>
        <h2><?php echo $this->escapeHtml($this->translate('Visitors today')); ?></h2>
        <?php $this->graph->Values($this->visistorsHours); ?>
        <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
        <?php echo $this->graph->FetchJavascript(); ?>
    <?php endif; ?>

    <?php if(!empty($this->visistorsDays)): ?>
        <h2><?php echo $this->escapeHtml($this->translate('Visitors this month')); ?></h2>
        <?php $this->graph->Values($this->visistorsDays); ?>
        <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
        <?php echo $this->graph->FetchJavascript(); ?>
    <?php endif; ?>

    <?php if(!empty($this->visistorsMonths)): ?>
        <h2><?php echo $this->escapeHtml($this->translate('Visitors this year')); ?></h2>
        <?php $this->graph->Values($this->visistorsMonths); ?>
        <?php echo $this->graph->Fetch('Bar3DGraph', false); ?>
        <?php echo $this->graph->FetchJavascript(); ?>
    <?php endif; ?>
</div>
