<div id="footer-wrapper">
    <footer class="container" id="site-footer">
        <div class="row">
            <div class="4u">
                <section class="first">
                    <h2>Ipsum et phasellus</h2>
                    <ul class="link-list">
                        <li><a href="#">Mattis et quis rutrum sed accumsan</a>
                        <li><a href="#">Suspendisse amet varius nibh</a>
                        <li><a href="#">Suspenddapibus amet mattis quis</a>
                        <li><a href="#">Rutrum accumsan eu varius</a>
                        <li><a href="#">Nibh lorem sed dolore et ipsum.</a>
                    </ul>
                </section>
            </div>
            <div class="4u">
                <section>
                    <h2>Lorem mattis dolor</h2>
                    <ul class="link-list">
                        <li><a href="#">Duis neque nisi dapibus sed</a>
                        <li><a href="#">Suspenddapibus amet mattis quis</a>
                        <li><a href="#">Rutrum accumsan eu varius</a>
                        <li><a href="#">Nibh lorem sed dolore et ipsum.</a>
                        <li><a href="#">Mattis et quis rutrum sed accumsan</a>
                    </ul>
                </section>
            </div>
            <div class="4u">
                <section>
                    <h2>Mattis quis tempus</h2>
                    <ul class="link-list">
                        <li><a href="#">Suspendisse amet varius nibh</a>
                        <li><a href="#">Suspenddapibus amet mattis quis</a>
                        <li><a href="#">Rutrum accumsan eu varius</a>
                        <li><a href="#">Nibh lorem sed dolore et ipsum.</a>
                        <li><a href="#">Duis neque nisi dapibus sed</a>
                    </ul>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="12u">
                <div class="divider"></div>
            </div>
        </div>
        <div class="row">
            <div class="12u">
                <div id="copyright">
                    &copy; <?php echo $this->escapeHtml($this->config()->get('site_name')); ?>. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a> | Images: <a href="http://fotogrph.com">fotogrph</a>
                </div>
            </div>
        </div>
    </footer>
</div>
