<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Admin
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
/** @var $this \Zend\View\Renderer\PhpRenderer */

?>

<div class="dashboard<?php if(empty($this->dashboardWelcome)): ?> hide<?php endif; ?>" id="dashboard">
    <a href="#close" class="dashboard-close floatR"><?php echo $this->escapeHtml($this->translate('Close')); ?></a>

    <div class="dashboard-content">
        <h3><?php echo $this->escapeHtml($this->translate('Welcome on your new website GotCms!')); ?></h3>
        <p class="about-description"><?php echo $this->escapeHtml($this->translate('Introduction')); ?></p>
        <div class="dashboard-column-container">

            <p class="dashboard-dismiss">
                <?php echo $this->escapeHtml($this->translate('You know what you do?')); ?>
                <a href="#close" class="dashboard-close"><?php echo $this->escapeHtml($this->translate('Close message.')); ?></a>
            </p>
        </div>
    </div>
</div>

<div class="widget-column floatL" id="sortable1">
    <div class="widget-box" id="fast-links">
        <h3 class="header">
            <span><?php echo $this->escapeHtml($this->translate('Fast links')); ?></span>
        </h3>
        <div class="inside">
            <ul>
                <li><a href="<?php echo $this->url('documentCreate'); ?>"><?php echo $this->escapeHtml($this->translate('Create document')); ?></a></li>
                <li><a href="<?php echo $this->url('userList'); ?>"><?php echo $this->escapeHtml($this->translate('User list')); ?></a></li>
                <li><a href="<?php echo $this->url('configGeneral'); ?>"><?php echo $this->escapeHtml($this->translate('General configuration')); ?></a></li>
                <li><a href="<?php echo $this->url('translationCreate'); ?>"><?php echo $this->escapeHtml($this->translate('Add translation')); ?></a></li>
                <li><a href="<?php echo $this->url('media'); ?>"><?php echo $this->escapeHtml($this->translate('File manager')); ?></a></li>
            </ul>
        </div>
    </div>

    <?php foreach($this->customeWidgets as $widget): ?>
        <?php if(empty($widget['id']) or empty($widget['title']) or empty($widget['content'])): ?>
            <?php continue; ?>
        <?php endif; ?>
        <div class="widget-box" id="<?php echo $this->escapeHtml(!empty($widget['id']) ? $widget['id'] : ''); ?>">
            <h3 class="header">
                <span><?php echo $this->escapeHtml($this->translate(!empty($widget['title']) ? $widget['title'] : '')); ?></span>
            </h3>
            <div class="inside">
                <?php echo !empty($widget['content']) ? $widget['content'] : ''; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="widget-column floatR" id="sortable2">
    <div class="widget-box" id="stats">
        <h3 class="header">
            <span><?php echo $this->escapeHtml($this->translate('Stats')); ?></span>
        </h3>
        <div class="inside">

            <div class="table floatL">
                <p class="sub"><?php echo $this->escapeHtml($this->translate('Content')); ?></p>
                <table>
                    <tbody>
                        <?php foreach($this->contentStats as $stats): ?>
                            <tr>
                                <td class="first">
                                    <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $stats['count']; ?></a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $this->escapeHtml($this->translate($stats['label'])); ?></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="table floatL">
                <p class="sub"><?php echo $this->escapeHtml($this->translate('Stats')); ?></p>
                <table>
                    <tbody>
                        <?php foreach($this->userStats as $stats): ?>
                            <tr>
                                <td class="first">
                                    <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $stats['count']; ?></a>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $this->escapeHtml($this->translate($stats['label'])); ?></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <div class="version">
                <span>
                    <?php echo $this->escapeHtml(sprintf($this->translate('You use GotCms %s'), $this->version)); ?>
                    <?php if(!$this->versionIsLatest): ?>
                        <a class="button" href="https://github.com/PierreRambaud/GotCms"><?php echo $this->escapeHtml(sprintf($this->translate('Update to GotCms %s'), $this->versionLatest)); ?></a>
                    <?php endif; ?>
                </span>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    Gc.initDashBoard($.parseJSON('<?php echo $this->escapeJs($this->dashboardSortable); ?>'), '<?php echo $this->escapeJs($this->url('dashboardSave')); ?>');
</script>
