<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Content
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php echo $this->form()->openTag($this->form); ?>
    <button class="btn-in-tab btn btn-warning btn-sm" id="input-save" type="submit">
        <i class="glyphicon glyphicon-floppy-disk"></i>
        <?php echo $this->escapeHtml($this->translate('Save')); ?>
    </button>
    <div id="tabs" style="margin-bottom:20px">
        <?php echo $this->tabs; ?>

        <?php $fieldsets = $this->form->getFieldsets(); ?>
        <?php foreach ($fieldsets as $tab_id => $fieldset): ?>
            <div id="<?php echo $this->escapeHtml($tab_id); ?>" class="form-horizontal">
                <?php $elements = $fieldset->getElements(); ?>
                <?php foreach ($elements as $element): ?>
                    <div class="form-group">
                        <?php if ($element->getName() == 'more_information'): ?>
                            <div class="col-lg-2">
                                <label class="control-label"><?php echo $this->escapeHtml($this->translate('Preview')); ?></label>
                            </div>

                            <div class="col-lg-10">
                                <a class="btn btn-link" target="_blank" href="<?php echo $this->escapeHtml($this->document->getUrl()); ?>?preview=true"><?php echo $this->escapeHtml($this->document->getUrl()); ?></a>
                            </div>
                        <?php else: ?>
                            <?php $content = $element->getAttribute('content'); ?>
                            <?php if (!empty($content)): ?>
                                <?php echo $content; ?>
                            <?php else: ?>
                                <?php if ($element->getAttribute('type') != 'hidden'): ?>
                                    <?php if ($element->getLabel()): ?>
                                        <div class="col-lg-2">
                                            <?php echo $this->formLabel($element); ?>
                                            <?php $description = $element->getAttribute('description'); ?>
                                            <?php if (!empty($description)): ?>
                                                <p class="help-block"><?php echo $this->escapeHtml($this->translate($description)); ?></p>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <div class="col-lg-10">
                                    <?php echo $this->formElement($element); ?>
                                    <?php echo $this->formElementErrors($element, array('class' => 'text-danger')); ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php echo $this->form()->closeTag($this->form); ?>

<script type="text/javascript">
$(function(){
    jQuery('#tabs').tabs();
    Gc.saveCommand();
    Gc.checkDataChanged();
});
</script>
