<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<form action="<?php echo $this->escape($this->form->getAttribute('action')); ?>" class="simple-form">
    <div id="tabs" style="margin-bottom:20px">
        <?php echo $this->tabs; ?>
        <?php $fieldsets = $this->form->getFieldsets(); ?>
        <?php foreach($fieldsets as $tab_id => $fieldset): ?>
            <div id="<?php echo $this->escape($tab_id); ?>">
                <?php $elements = $fieldset->getElements(); ?>
                <?php foreach($elements as $element): ?>
                    <div>
                        <?php $content = $element->getAttribute('content'); ?>
                        <?php if(!empty($content)): ?>
                            <?php echo $content; ?>
                        <?php else: ?>
                            <label class="required" for="name"><?php echo $this->escape($this->translator($element->getAttribute('label'))); ?></label>

                            <?php echo $this->formElement($element); ?>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
</form>
<script type="text/javascript">
    jQuery('#tabs').tabs();
</script>
