<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php echo $this->form()->openTag($this->form); ?>
    <div class="form-group">
        <?php echo $this->formLabel($this->form->get('name')); ?>
        <div class="col-lg-10">
            <?php echo $this->formElement($this->form->get('name')); ?>
            <?php echo $this->formElementErrors($this->form->get('name'), array('class' => 'text-danger')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($this->form->get('identifier')); ?>
        <div class="col-lg-10">
            <?php echo $this->formElement($this->form->get('identifier')); ?>
            <?php echo $this->formElementErrors($this->form->get('identifier'), array('class' => 'text-danger')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($this->form->get('description')); ?>
        <div class="col-lg-10">
            <?php echo $this->formElement($this->form->get('description')); ?>
            <?php echo $this->formElementErrors($this->form->get('description'), array('class' => 'text-danger')); ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($this->form->get('content')); ?>
        <div class="col-lg-10">
            <?php echo $this->formElement($this->form->get('content')); ?>
            <?php echo $this->formElementErrors($this->form->get('content'), array('class' => 'text-danger')); ?>
        </div>
    </div>

    <input type="submit" id="input-save" class="btn btn-warning" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" name="submit">
<?php echo $this->form()->closeTag($this->form); ?>

<script type="text/javascript">
    Gc.initCodeMirror('content');
    Gc.saveCommand();
    Gc.checkDataChanged();
</script>
