<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<form class="simple-form form-horizontal" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <?php if (!empty($this->infos)): ?>
        <div id="datatype-infos">
            <a href="#"><?php echo $this->escapeHtml($this->translate('Display/Hide informations')); ?></a>

            <div class="hide">
                <?php echo $this->infos; ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="form-group">
        <label class="required control-label col-lg-2" for="name"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        <div class="col-lg-10">
            <input type="name" class="form-control" value="<?php echo $this->escapeHtml($this->form->getValue('name')); ?>" id="name" name="name">
            <?php echo $this->formElementErrors($this->form->get('name')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="required control-label col-lg-2" for="model"><?php echo $this->escapeHtml($this->translate('Model')); ?></label>
        <div class="col-lg-10">
            <select class="form-control" id="model" name="model">
                <?php $options = $this->form->get('model')->getValueOptions(); ?>
                <?php foreach ($options as $option_id => $option_value): ?>
                    <option <?php if ($option_id == $this->form->getValue('model')): ?>selected="selected" <?php endif; ?>label="<?php echo $this->escapeHtml($this->translate($option_value)); ?>" value="<?php echo $this->escapeHtml($option_value); ?>"><?php echo $this->escapeHtml($option_value); ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <?php echo $this->formElementErrors($this->form->get('model')); ?>
    </div>

    <?php if ($this->form->has('prevalue-editor')): ?>
        <?php $fieldset = $this->form->get('prevalue-editor'); ?>
        <?php foreach ($fieldset->getElements() as $element): ?>
            <div>
                <?php $content = $element->getAttribute('content'); ?>
                <?php if (!empty($content)): ?>
                    <?php echo $content; ?>
                <?php else: ?>
                    <div class="form-group">
                        <?php $id = $element->getAttribute('id'); ?>
                        <?php $label = $element->getAttribute('label'); ?>

                        <?php if (empty($id)): ?>
                            <?php $id = 'element' . mt_rand(); ?>
                            <?php $element->setAttribute('id', $id); ?>
                        <?php endif; ?>

                        <?php if (!empty($label)): ?>
                            <label class="required control-label col-lg-2" for="<?php echo $this->escapeHtml($this->translate($id)); ?>"><?php echo $this->escapeHtml($this->translate($label)); ?></label>
                        <?php endif; ?>

                        <div class="col-lg-10">
                            <?php echo $this->formElement($element); ?>
                            <?php echo $this->formElementErrors($element); ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <input type="submit" id="input-save" class="btn btn-warning" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" id="submit" name="submit">
</form>

<script type="text/javascript">
    $('#datatype-infos > a').on('click', function() {
        $(this).next('div').toggleClass('hide');
    });
</script>
