<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<form class="simple-form" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <?php if (!empty($this->infos)): ?>
        <div id="datatype-infos">
            <a href="#"><?php echo $this->escapeHtml($this->translate('Display/Hide informations')); ?></a>

            <?php echo $this->infos; ?>
        </div>
    <?php endif; ?>

    <div>
        <label class="required" for="name"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        <input type="name" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('name')); ?>" id="name" name="name">

        <?php echo $this->formElementErrors($this->form->get('name')); ?>
    </div>
    <div>
        <label class="required" for="model"><?php echo $this->escapeHtml($this->translate('Model')); ?></label>
        <select class="input-select" id="model" name="model">
            <?php $options = $this->form->get('model')->getValueOptions(); ?>
            <?php foreach ($options as $option_id => $option_value): ?>
                <option <?php if ($option_id == $this->form->getValue('model')): ?>selected="selected" <?php endif; ?>label="<?php echo $this->escapeHtml($this->translate($option_value)); ?>" value="<?php echo $this->escapeHtml($option_value); ?>"><?php echo $this->escapeHtml($option_value); ?></option>
            <?php endforeach; ?>
        </select>

        <?php echo $this->formElementErrors($this->form->get('model')); ?>
    </div>

    <?php $fieldset = $this->form->get('prevalue-editor'); ?>
    <?php if (!empty($fieldset)): ?>
        <?php foreach ($fieldset->getElements() as $element): ?>
            <div>
                <?php $content = $element->getAttribute('content'); ?>
                <?php if (!empty($content)): ?>
                    <?php echo $content; ?>
                <?php else: ?>
                    <?php $id = $element->getAttribute('id'); ?>
                    <?php $label = $element->getAttribute('label'); ?>

                    <?php if (empty($id)): ?>
                        <?php $id = 'element' . mt_rand(); ?>
                        <?php $element->setAttribute('id', $id); ?>
                    <?php endif; ?>

                    <?php if (!empty($label)): ?>
                        <label class="required" for="<?php echo $this->escapeHtml($this->translate($id)); ?>"><?php echo $this->escapeHtml($this->translate($label)); ?></label>
                    <?php endif; ?>

                    <?php echo $this->formElement($element); ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <div>
        <input type="submit" id="input-save" class="input-submit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" id="submit" name="submit">
    </div>
</form>

<script type="text/javascript">
    $('#datatype-infos > a').on('click', function() {
        $(this).next('dl').toggle();
    });
</script>
