<?php
/**
 * This source file is part of Got CMS.
 *
 * Got CMS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Got CMS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Got CMS. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php $infos_form = $this->form->get('infos'); ?>
<?php $views_form = $this->form->get('views'); ?>
<?php $tabs_form = $this->form->get('tabs')->getFieldsets(); ?>
<?php $properties_forms = $this->form->get('properties')->getFieldsets(); ?>
<?php $datatypes_options = $this->form->get('properties')->get('datatypes')->getAttribute('options'); ?>
<?php $errors = $this->form->getMessages(); ?>

<ul>
    <li><a href="#tabs-1"><?php echo $this->escapeHtml($this->translate('Infos')); ?></a></li>
    <li><a href="#tabs-2"><?php echo $this->escapeHtml($this->translate('Views')); ?></a></li>
    <li><a href="#tabs-3"><?php echo $this->escapeHtml($this->translate('Properties')); ?></a></li>
    <li><a href="#tabs-4"><?php echo $this->escapeHtml($this->translate('Tabs')); ?></a></li>
</ul>
<form id="development-form" enctype="application/x-www-form-urlencoded" action="<?php echo $this->form->getAttribute('action'); ?>" method="post">
    <dl id="tabs-1">
        <dt>
            <label for="infos-name" class="optional"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        </dt>
        <dd>
            <input type="text" name="infos[name]" id="infos-name" value="<?php echo $infos_form->get('name')->getAttribute('value'); ?>">
            <?php if(!empty($errors['infos']['name'])): ?>
                <?php echo $this->formErrors($errors['infos']['name']); ?>
            <?php endif; ?>
        </dd>
        <dt>
            <label for="infos-description" class="optional"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
        </dt>
        <dd>
            <input type="text" name="infos[description]" id="infos-description" value="<?php echo $infos_form->get('description')->getAttribute('value'); ?>">
            <?php if(!empty($errors['infos']['description'])): ?>
                <?php echo $this->formErrors($errors['infos']['description']); ?>
            <?php endif; ?>
        </dd>
        <dt>
            <label for="infos-icon_id" class="optional"><?php echo $this->escapeHtml($this->translate('Icon')); ?></label>
        </dt>
        <dd>
            <select name="infos[icon_id]" id="infos-icon_id">

            </select>
            <?php if(!empty($errors['infos']['icon_id'])): ?>
                <?php echo $this->formErrors($errors['infos']['icon_id']); ?>
            <?php endif; ?>
        </dd>
    </dl>

    <dl id="tabs-2">
        <dt>
            <label for="views-default_view" class="required"><?php echo $this->escapeHtml($this->translate('Default view')); ?></label>
        </dt>

        <dd>
            <select name="views[default_view]" id="views-default_view">
                <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                <?php $default_view = $views_form->get('default_view'); ?>
                <?php $default_view_option = $default_view->getAttribute('options'); ?>
                <?php foreach($default_view_option as $option_id => $option_value): ?>
                    <option value="<?php echo $option_id; ?>"<?php if($default_view->getAttribute('value') == $option_id): ?> selected="selected"<?php endif; ?>><?php echo $this->escapeHtml($option_value); ?> </option>
                <?php endforeach; ?>
            </select>

            <?php if(!empty($errors['views']['default_view'])): ?>
                <?php echo $this->formErrors($errors['views']['default_view']); ?>
            <?php endif; ?>
        </dd>
        <dt>
            <label for="views-available_views" class="optional"><?php echo $this->escapeHtml($this->translate('Add view')); ?></label>
        </dt>
        <dd>
            <select name="views[available_views]" id="views-available_views" multiple="multiple">
                <?php $available_views = $views_form->get('available_views'); ?>
                <?php $default_view_option = $available_views->getAttribute('options'); ?>
                <?php foreach($default_view_option as $option_id => $option_value): ?>
                    <option value="<?php echo $option_id; ?>"<?php if($available_views->getAttribute('value') == $option_id): ?> selected="selected"<?php endif; ?>><?php echo $this->escapeHtml($option_value); ?> </option>
                <?php endforeach; ?>
            </select>

            <?php if(!empty($errors['views']['available_views'])): ?>
                <?php echo $this->formErrors($errors['views']['available_views']); ?>
            <?php endif; ?>
        </dd>
    </dl>

    <dl id="tabs-3">
        <dt>
            <label for="properties-name" class="optional"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        </dt>
        <dd>
            <input type="text" name="properties[name]" id="properties-name" value="">
        </dd>
        <dt>
            <label for="properties-identifier" class="optional"><?php echo $this->escapeHtml($this->translate('Identifier')); ?></label>

        </dt>
        <dd>
            <input type="text" name="properties[identifier]" id="properties-identifier" value="">
        </dd>
        <dt>
            <label for="properties-tab" class="required"><?php echo $this->escapeHtml($this->translate('Tab')); ?></label>
        </dt>
        <dd>
            <select name="properties[tab]" id="properties-tab" class="select-tab">
                <option value="" label="-- Select tab --" selected="selected">-- Select tab --</option>
                <?php foreach($tabs_form as $tab_form): ?>
                    <option value="<?php echo $tab_form->get('tab_id')->getAttribute('value'); ?>"><?php echo $tab_form->get('name')->getAttribute('value'); ?></option>
                <?php endforeach; ?>
            </select>
        </dd>

        <dt>
            <label for="properties-datatype" class="required"><?php echo $this->escapeHtml($this->translate('Datatype')); ?></label>
        </dt>
        <dd>
            <select name="properties[datatype]" id="properties-datatype" class="select-datatype">
                <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                <?php foreach($datatypes_options as $datatype_id => $datatype_name): ?>
                    <option value="<?php echo $datatype_id; ?>"><?php echo $this->escapeHtml($datatype_name); ?> </option>
                <?php endforeach; ?>
            </select>
        </dd>
        <dt>
            <label for="properties-description" class="optional"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
        </dt>
        <dd>
            <input type="text" name="properties[description]" id="properties-description" value="">
        </dd>
        <dt>
            <label for="properties-required" class="optional"><?php echo $this->escapeHtml($this->translate('Required')); ?></label>
        </dt>

        <dd>
            <input type="checkbox" name="properties[required]" id="properties-required" value="1">
        </dd>
        <dt>&nbsp;</dt>
        <dd>
            <button name="properties[add]" id="property_add" type="button" class="button-add button-add-property"><?php echo $this->escapeHtml($this->translate('Add property')); ?></button>
        </dd>
        <dt><?php echo $this->escapeHtml($this->translate('Properties')); ?></dt>
        <dd>
            <div id="properties-tabs-content" class="tabs">
                <ul>
                    <?php foreach($tabs_form as $tab_form): ?>
                        <li>
                            <?php $name = $tab_form->get('name')->getAttribute('value'); ?>
                            <a href="#tabs-properties-<?php echo $tab_form->get('tab_id')->getAttribute('value'); ?>">
                                <?php echo $name; ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <?php foreach($tabs_form as $tab_form): ?>
                    <?php $tab_id = $tab_form->get('tab_id')->getAttribute('value'); ?>
                    <div id="tabs-properties-<?php echo $tab_id; ?>">
                        <ul class="sortable connected-sortable ui-helper-reset">
                            <?php foreach($properties_forms as $property): ?>
                                <?php if($property->get('tab')->getAttribute('value') != $tab_id): ?>
                                    <?php continue; ?>
                                <?php endif; ?>

                                <li>
                                    <?php $property_id = (int)$property->get('property_id')->getAttribute('value'); ?>
                                    <?php $property_form_id = 'property'.$property->get('property_id')->getAttribute('value'); ?>
                                    <h3><?php echo $this->escapeHtml($property_id); ?></h3>
                                    <dl>
                                        <dt>
                                            <label class="optional" for="properties-name-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
                                        </dt>
                                        <dd>
                                            <input type="text" value="<?php echo $this->escapeHtml($property->get('name')->getAttribute('value')); ?>" id="properties-name-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][name]">
                                            <?php if(!empty($errors['properties'][$property_form_id]['name'])): ?>
                                                <?php echo $this->formErrors($errors['properties'][$property_form_id]['name']); ?>
                                            <?php endif; ?>
                                        </dd>
                                        <dt>
                                            <label class="optional" for="properties-identifier-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Identifier')); ?></label>
                                        </dt>
                                        <dd>
                                            <input type="text" value="<?php echo $this->escapeHtml($property->get('identifier')->getAttribute('value')); ?>" id="properties-identifier-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][identifier]">
                                            <?php if(!empty($errors['properties'][$property_form_id]['identifier'])): ?>
                                                <?php echo $this->formErrors($errors['properties'][$property_form_id]['identifier']); ?>
                                            <?php endif; ?>
                                        </dd>
                                        <dt>
                                            <label class="optional" for="properties-datatype-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Datatype')); ?></label>
                                        </dt>
                                        <dd>
                                            <select class="select-datatype" id="properties-datatype-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][datatype]">
                                                <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                                                <?php foreach($datatypes_options as $datatype_id => $datatype_name): ?>
                                                    <option value="<?php echo $datatype_id; ?>"<?php if($datatype_id == $property->get('datatype')->getAttribute('value')): ?> selected="selected"<?php endif; ?>><?php echo $this->escapeHtml($datatype_name); ?> </option>
                                                <?php endforeach; ?>
                                            </select>

                                            <?php if(!empty($errors['properties'][$property_form_id]['datatype'])): ?>
                                                <?php echo $this->formErrors($errors['properties'][$property_form_id]['datatype']); ?>
                                            <?php endif; ?>
                                        </dd>
                                        <dt>
                                            <label class="optional" for="properties-description-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
                                        </dt>
                                        <dd>
                                            <input type="text" value="<?php echo $this->escapeHtml($property->get('description')->getAttribute('value')); ?>" id="properties-description-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][description]">
                                            <?php if(!empty($errors['properties'][$property_form_id]['description'])): ?>
                                                <?php echo $this->formErrors($errors['properties'][$property_form_id]['description']); ?>
                                            <?php endif; ?>
                                        </dd>
                                        <dt>
                                            <label class="optional" for="properties-required-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Required')); ?></label>
                                        </dt>
                                        <dd>
                                            <?php
                                                $value = $property->get('required')->getAttribute('value');
                                                $checkedValue = $property->get('required')->getAttribute('checkedValue');
                                            ?>
                                            <input<?php if($value == $checkedValue):?> checked="checked"<?php endif; ?> type="checkbox" value="<?php echo $value; ?>" id="properties-required-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][required]">

                                            <?php if(!empty($errors['properties'][$property_form_id]['required'])): ?>
                                                <?php echo $this->formErrors($errors['properties'][$property_form_id]['required']); ?>
                                            <?php endif; ?>
                                        </dd>
                                        <dd>
                                            <input type="hidden" id="properties-tab-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][tab]" value="<?php echo (int)$property->get('tab')->getAttribute('value'); ?>">
                                            <button type="button" value="<?php echo $property_id; ?>" class="delete-property"><?php echo $this->escapeHtml($this->translate('Delete')); ?></button>
                                        </dd>
                                    </dl>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endforeach; ?>
            </div>
        </dd>
    </dl>

    <dl id="tabs-4">
        <dt>
            <label for="tabs-addname" class="optional"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        </dt>
        <dd>
            <input type="text" name="tabs[addname]" id="tabs-addname" value="">
        </dd>
        <dt>
            <label for="tabs-adddescription" class="optional"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
        </dt>
        <dd>
            <input type="text" name="tabs[adddescription]" id="tabs-adddescription" value="">
        </dd>
        <dt>&nbsp;</dt>
        <dd>
            <button name="tabs[add]" id="tabs-add" type="button" class="button-add button-add-tab"><?php echo $this->escapeHtml($this->translate('Add Tab')); ?></button>
        </dd>

        <dt><?php echo $this->escapeHtml($this->translate('Tabs')); ?></dt>
        <dd>
            <ul id="tabs" class="sortable ui-sortable">
            <?php foreach($tabs_form as $tab_form): ?>
                <li>
                    <?php $name = $tab_form->get('name')->getAttribute('value'); ?>
                    <?php $description = $tab_form->get('description')->getAttribute('value'); ?>
                    <?php $tab_id = 'tab'.$tab_form->get('tab_id')->getAttribute('value'); ?>
                    <input type="hidden" value="<?php echo $name; ?>" name="tabs[<?php echo $tab_id; ?>][name]">
                    <input type="hidden" value="<?php echo $description; ?>" name="tabs[<?php echo $tab_id; ?>][description]">
                    <span><?php echo $name; ?></span>
                    <span><?php echo $description; ?></span>
                    <button value="<?php echo (int)$tab_form->get('tab_id')->getAttribute('value'); ?>" class="delete-tab" type="button">delete</button>
                </li>
            <?php endforeach; ?>
            </ul>
        </dd>
    </dl>

    <div>
        <input type="submit" name="submit" id="submit" value="Submit">
    </div>
</form>
