<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php $infos_form = $this->form->get('infos'); ?>
<?php $views_form = $this->form->get('views'); ?>
<?php $tabs_form = $this->form->get('tabs')->getFieldsets(); ?>
<?php $properties_forms = $this->form->get('properties')->getFieldsets(); ?>
<?php $datatypes_options = $this->form->get('properties')->get('datatypes')->getValueOptions(); ?>

<form id="development-form" enctype="application/x-www-form-urlencoded" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" class="simple-form">
    <input id="input-save" type="image" src="<?php echo $this->cdn('backend/images/save.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Save and publish')); ?>">

    <div class="tabs">
        <ul>
            <li><a href="#tabs-1"><?php echo $this->escapeHtml($this->translate('Infos')); ?></a></li>
            <li><a href="#tabs-2"><?php echo $this->escapeHtml($this->translate('Views')); ?></a></li>
            <li><a href="#tabs-3"><?php echo $this->escapeHtml($this->translate('Properties')); ?></a></li>
            <li><a href="#tabs-4"><?php echo $this->escapeHtml($this->translate('Tabs')); ?></a></li>
        </ul>
        <div id="tabs-1">
            <div>
                <label for="infos-name" class="optional"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
                <input class="input-text" type="text" name="infos[name]" id="infos-name" value="<?php echo $infos_form->get('name')->getValue(); ?>">

                <?php echo $this->formElementErrors($this->form->get('infos')->get('name')); ?>
            </div>
            <div>
                <label for="infos-description" class="optional"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
                <input class="input-text" type="text" name="infos[description]" id="infos-description" value="<?php echo $infos_form->get('description')->getValue(); ?>">

                <?php echo $this->formElementErrors($this->form->get('infos')->get('description')); ?>
            </div>
            <div>
                <label for="infos-icon_id" class="optional"><?php echo $this->escapeHtml($this->translate('Icon')); ?></label>
                <select class="input-select" name="infos[icon_id]" id="infos-icon_id">
                    <?php $icons = $infos_form->get('icon_id')->getValueOptions(); ?>
                    <?php foreach ($icons as $option): ?>
                        <option value="<?php echo $option->getId(); ?>"<?php if ($infos_form->get('icon_id')->getValue() == $option->getId()): ?> selected="selected"<?php endif; ?> style="background:url(<?php echo $this->escapeHtml($option->getUrl()); ?>) no-repeat; padding-left:20px;"><?php echo $this->escapeHtml($option->getName()); ?> </option>
                    <?php endforeach; ?>
                </select>

                <?php echo $this->formElementErrors($this->form->get('infos')->get('icon_id')); ?>
            </div>
            <?php $dependency = $infos_form->get('infos[dependency]'); ?>
            <?php if (!empty($dependency)): ?>
                <div>
                    <label><?php echo $this->escapeHtml($this->translate('Available children')); ?></label>

                    <?php echo $this->formElement($infos_form->get('infos[dependency]')); ?>

                <?php echo $this->formElementErrors($this->form->get('infos')->get('infos[dependency]')); ?>
                </div>
            <?php endif; ?>
        </div>

        <div id="tabs-2">
            <div>
                <label for="views-default_view" class="required"><?php echo $this->escapeHtml($this->translate('Default view')); ?></label>
                <select class="input-select" name="views[default_view]" id="views-default_view">
                    <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                    <?php $default_view = $views_form->get('default_view'); ?>
                    <?php $default_view_option = $default_view->getValueOptions(); ?>
                    <?php foreach ($default_view_option as $option_id => $option_value): ?>
                        <option value="<?php echo $option_id; ?>"<?php if ($default_view->getValue() == $option_id): ?> selected="selected"<?php endif; ?>><?php echo $this->escapeHtml($option_value); ?> </option>
                    <?php endforeach; ?>
                </select>

                <?php echo $this->formElementErrors($this->form->get('views')->get('default_view')); ?>
            </div>
            <div>
                <label for="views-available_views" class="optional"><?php echo $this->escapeHtml($this->translate('Add view')); ?></label>
                <select class="input-select" name="views[available_views][]" id="views-available_views" multiple="multiple">
                    <?php $available_views = $views_form->get('available_views'); ?>
                    <?php $default_view_option = $available_views->getValueOptions(); ?>
                    <?php $values = $available_views->getValue(); ?>
                    <?php foreach ($default_view_option as $option_id => $option_value): ?>
                        <option value="<?php echo $option_id; ?>"<?php if (!empty($values[$option_id])): ?> selected="selected"<?php endif; ?>><?php echo $this->escapeHtml($option_value); ?> </option>
                    <?php endforeach; ?>
                </select>

                <?php echo $this->formElementErrors($this->form->get('views')->get('available_views')); ?>
            </div>
        </div>

        <div id="tabs-3">
            <button id="display-property" class="button-add"><?php echo $this->escapeHtml($this->translate('Show / Hide form create datatype')); ?></button>
            <div class="hide">
                <div>
                    <label for="properties-name" class="optional"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
                    <input class="input-text" type="text" name="properties[name]" id="properties-name" value="">
                </div>
                <div>
                    <label for="properties-identifier" class="optional"><?php echo $this->escapeHtml($this->translate('Identifier')); ?></label>
                    <input class="input-text" type="text" name="properties[identifier]" id="properties-identifier" value="">
                </div>
                <div>
                    <label for="properties-tab" class="required"><?php echo $this->escapeHtml($this->translate('Tab')); ?></label>
                    <select name="properties[tab]" id="properties-tab" class="input-select select-tab">
                        <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                        <?php foreach ($tabs_form as $tab_form): ?>
                            <option value="<?php echo $tab_form->get('tab_id')->getValue(); ?>"><?php echo $tab_form->get('name')->getValue(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div>
                    <label for="properties-datatype" class="required"><?php echo $this->escapeHtml($this->translate('Datatype')); ?></label>
                    <select name="properties[datatype]" id="properties-datatype" class="input-select select-datatype">
                        <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                        <?php foreach ($datatypes_options as $datatype_id => $datatype_name): ?>
                            <option value="<?php echo $datatype_id; ?>"><?php echo $this->escapeHtml($datatype_name); ?> </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label for="properties-description" class="optional"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
                    <input class="input-text" type="text" name="properties[description]" id="properties-description" value="">
                </div>
                <div>
                    <label for="properties-required" class="optional"><?php echo $this->escapeHtml($this->translate('Required')); ?></label>
                    <div class="input-checkbox">
                        <input type="checkbox" name="properties[required]" class="input-checkbox" id="properties-required" value="1">
                        <label for="properties-required"></label>
                    </div>
                </div>
                <div>
                    <button name="properties[add]" id="property-add" type="button" class="button-add button-add-property"><?php echo $this->escapeHtml($this->translate('Add')); ?></button>
                </div>
            </div>
            <div>
                <?php echo $this->escapeHtml($this->translate('Properties')); ?>
                <div id="properties-tabs-content" class="tabs">
                    <ul>
                        <?php foreach ($tabs_form as $tab_form): ?>
                            <li>
                                <?php $name = $tab_form->get('name')->getValue(); ?>
                                <a href="#tabs-properties-<?php echo $tab_form->get('tab_id')->getValue(); ?>">
                                    <?php echo $name; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>

                    <?php foreach ($tabs_form as $tab_form): ?>
                        <?php $tab_id = $tab_form->get('tab_id')->getValue(); ?>
                        <div id="tabs-properties-<?php echo $tab_id; ?>">
                            <div class="sortable connected-sortable ui-helper-reset">
                                <?php foreach ($properties_forms as $property): ?>
                                    <?php if ($property->get('tab')->getValue() != $tab_id): ?>
                                        <?php continue; ?>
                                    <?php endif; ?>

                                        <div>
                                            <?php $property_id = (int)$property->get('property_id')->getValue(); ?>
                                            <?php $property_form_id = 'property'.$property->get('property_id')->getValue(); ?>
                                            <h3><a href="#section<?php echo $property_id; ?>"><?php echo $this->escapeHtml(sprintf('%s (%s)', $property->get('name')->getValue(), $property->get('identifier')->getValue())); ?></a></h3>
                                            <dl>
                                                <dt>
                                                    <label class="optional" for="properties-name-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
                                                </dt>
                                                <dd>
                                                    <input class="input-text" type="text" value="<?php echo $this->escapeHtml($property->get('name')->getValue()); ?>" id="properties-name-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][name]">

                                                    <?php if ($this->form->get('properties')->has($property_form_id)): ?>
                                                        <?php echo $this->formElementErrors($this->form->get('properties')->get($property_form_id)->get('name')); ?>
                                                    <?php endif; ?>
                                                </dd>
                                                <dt>
                                                    <label class="optional" for="properties-identifier-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Identifier')); ?></label>
                                                </dt>
                                                <dd>
                                                    <input class="input-text" type="text" value="<?php echo $this->escapeHtml($property->get('identifier')->getValue()); ?>" id="properties-identifier-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][identifier]">

                                                    <?php if ($this->form->get('properties')->has($property_form_id)): ?>
                                                        <?php echo $this->formElementErrors($this->form->get('properties')->get($property_form_id)->get('identifier')); ?>
                                                    <?php endif; ?>
                                                </dd>
                                                <dt>
                                                    <label class="optional" for="properties-datatype-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Datatype')); ?></label>
                                                </dt>
                                                <dd>
                                                    <select class="input-select select-datatype" id="properties-datatype-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][datatype]">
                                                        <option value=""><?php echo $this->escapeHtml($this->translate('-- Select --')); ?></option>
                                                        <?php foreach ($datatypes_options as $datatype_id => $datatype_name): ?>
                                                            <option value="<?php echo $datatype_id; ?>"<?php if ($datatype_id == $property->get('datatype')->getValue()): ?> selected="selected"<?php endif; ?>><?php echo $this->escapeHtml($datatype_name); ?> </option>
                                                        <?php endforeach; ?>
                                                    </select>

                                                    <?php if ($this->form->get('properties')->has($property_form_id)): ?>
                                                        <?php echo $this->formElementErrors($this->form->get('properties')->get($property_form_id)->get('datatype')); ?>
                                                    <?php endif; ?>
                                                </dd>
                                                <dt>
                                                    <label class="optional" for="properties-description-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
                                                </dt>
                                                <dd>
                                                    <input class="input-text" type="text" value="<?php echo $this->escapeHtml($property->get('description')->getValue()); ?>" id="properties-description-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][description]">

                                                    <?php if ($this->form->get('properties')->has($property_form_id)): ?>
                                                        <?php echo $this->formElementErrors($this->form->get('properties')->get($property_form_id)->get('description')); ?>
                                                    <?php endif; ?>
                                                </dd>
                                                <dt>
                                                    <label class="optional" for="properties-required-<?php echo $property_id; ?>"><?php echo $this->escapeHtml($this->translate('Required')); ?></label>
                                                </dt>
                                                <dd>
                                                    <?php
                                                        $value = $property->get('required')->getValue();
                                                        $checkedValue = $property->get('required')->getAttribute('checkedValue');
                                                    ?>
                                                    <div class="input-checkbox">
                                                        <input type="checkbox" name="properties[<?php echo $property_form_id; ?>][required]" class="input-checkbox" id="properties-required-<?php echo $property_id; ?>" value="<?php echo $value; ?>" <?php if ($value == $checkedValue):?> checked="checked"<?php endif; ?>>
                                                        <label for="properties-required-<?php echo $property_id; ?>"></label>
                                                    </div>

                                                    <?php if ($this->form->get('properties')->has($property_form_id)): ?>
                                                        <?php echo $this->formElementErrors($this->form->get('properties')->get($property_form_id)->get('required')); ?>
                                                    <?php endif; ?>
                                                </dd>
                                                <dd class="cb">
                                                    <input class="property-tab-id" type="hidden" id="properties-tab-<?php echo $property_id; ?>" name="properties[<?php echo $property_form_id; ?>][tab]" value="<?php echo (int)$property->get('tab')->getValue(); ?>">
                                                    <button type="button" value="<?php echo $property_id; ?>" class="button-delete delete-property"><?php echo $this->escapeHtml($this->translate('Delete')); ?></button>
                                                </dd>
                                            </dl>
                                        </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div id="tabs-4">
            <div>
                <label for="tabs-addname" class="optional"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
                <input class="input-text" type="text" name="tabs[addname]" id="tabs-addname" value="">
            </div>
            <div>
                <label for="tabs-adddescription" class="optional"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
                <input class="input-text" type="text" name="tabs[adddescription]" id="tabs-adddescription" value="">
            </div>
            <div>
                <button name="tabs[add]" id="tabs-add" type="button" class="button-add button-add-tab"><?php echo $this->escapeHtml($this->translate('Add Tab')); ?></button>
            </div>

            <div id="import-tab">
                <?php $tabs_list = $this->form->get('tabs')->get('tabs_list')->getValueOptions(); ?>
                <?php if (!empty($tabs_list)): ?>
                    <select class="input-select" id="import-tabs">
                        <?php foreach ($tabs_list as $tab): ?>
                            <option value="<?php echo $this->escapeHtml($tab->getId()); ?>"><?php echo $this->escapeHtml($tab->getName()); ?> (<?php echo $this->escapeHtml($tab->getDocumentType()->getName()); ?>)</option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
                <button id="import-tab-button" class="button-add"><?php echo $this->escapeHtml($this->translate('Import tab')); ?></button>
            </div>

            <div>
                <h3><?php echo $this->escapeHtml($this->translate('Tabs')); ?></h3>
                <ul id="tabs" class="sortable ui-sortable">
                <?php foreach ($tabs_form as $tab_form): ?>
                    <li class="clearfix">
                        <?php $name = $tab_form->get('name')->getValue(); ?>
                        <?php $description = $tab_form->get('description')->getValue(); ?>
                        <?php $tab_id = 'tab'.$tab_form->get('tab_id')->getValue(); ?>
                        <div class="hide floatL">
                            <input class="input-text" type="text" value="<?php echo $name; ?>" name="tabs[<?php echo $tab_id; ?>][name]">
                            <input class="input-text" type="text" value="<?php echo $description; ?>" name="tabs[<?php echo $tab_id; ?>][description]">
                        </div>
                        <div class="floatL">
                            <span><?php echo $name; ?></span>
                            <span><?php echo $description; ?></span>
                        </div>
                        <button value="<?php echo (int)$tab_form->get('tab_id')->getValue(); ?>" class="button-delete delete-tab floatR" type="button"><?php echo $this->escapeHtml($this->translate('Delete'));?> </button>
                    </li>
                <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</form>
