<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<form class="relative form-horizontal" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <div class="form-group">
        <label class="required control-label col-lg-2" for="name"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        <div class="col-lg-10">
            <input type="text" class="form-control" value="<?php echo $this->escapeHtml($this->form->getValue('name')); ?>" id="name" name="name">
            <?php echo $this->formElementErrors($this->form->get('name'), array('class' => 'text-danger')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="required control-label col-lg-2" for="identifier"><?php echo $this->escapeHtml($this->translate('Identifier')); ?></label>
        <div class="col-lg-10">
            <input type="text" class="form-control" value="<?php echo $this->escapeHtml($this->form->getValue('identifier')); ?>" id="identifier" name="identifier">
            <?php echo $this->formElementErrors($this->form->get('identifier'), array('class' => 'text-danger')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="required control-label col-lg-2" for="description"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
        <div class="col-lg-10">
            <input type="text" class="form-control" value="<?php echo $this->escapeHtml($this->form->getValue('description')); ?>" id="description" name="description">
            <?php echo $this->formElementErrors($this->form->get('description'), array('class' => 'text-danger')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="required control-label col-lg-2" for="layout-content"><?php echo $this->escapeHtml($this->translate('Content')); ?></label>
        <div class="col-lg-10">
            <textarea cols="80" rows="24" id="layout-content" name="content"><?php echo $this->escapeHtml($this->form->getValue('content')); ?></textarea>
            <?php echo $this->formElementErrors($this->form->get('content'), array('class' => 'text-danger')); ?>
        </div>
    </div>

    <input type="submit" id="input-save" class="btn btn-warning" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" id="submit" name="submit">
</form>
