<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<form class="simple-form" action="<?php echo $this->form->getAttribute('action'); ?>" method="post" enctype="application/x-www-form-urlencoded">
    <div>
        <label class="required" for="email"><?php echo $this->escapeHtml($this->translate('Name')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('name')); ?>" id="name" name="name">

        <?php echo $this->formElementErrors($this->form->get('name')); ?>
    </div>
    <div>
        <label class="required" for="email"><?php echo $this->escapeHtml($this->translate('Identifier')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('identifier')); ?>" id="identifier" name="identifier">

        <?php echo $this->formElementErrors($this->form->get('identifier')); ?>
    </div>
    <div>
        <label class="required" for="email"><?php echo $this->escapeHtml($this->translate('Description')); ?></label>
        <input type="text" class="input-text" value="<?php echo $this->escapeHtml($this->form->getValue('description')); ?>" id="description" name="description">

        <?php echo $this->formElementErrors($this->form->get('description')); ?>
    </div>
    <div>
        <label class="required" for="email"><?php echo $this->escapeHtml($this->translate('Content')); ?></label>
        <textarea cols="80" rows="24" id="layout-content" name="content"><?php echo $this->escapeHtml($this->form->getValue('content')); ?></textarea>

        <?php echo $this->formElementErrors($this->form->get('content')); ?>
    </div>
    <div>
        <input type="submit" id="input-save" class="input-submit" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>" id="submit" name="submit">
    </div>
</form>
