<table>
    <tr>
        <th><?php echo $this->escape($this->translator('Id')); ?></th>
        <th><?php echo $this->escape($this->translator('Name')); ?></th>
        <th><?php echo $this->escape($this->translator('Edit')); ?></th>
        <th><?php echo $this->escape($this->translator('Delete')); ?></th>
    </tr>
    <?php foreach($this->datatypes as $datatype): ?>
        <tr>
            <td><?php echo $datatype->getId(); ?></td>
            <td><?php echo $this->escape($datatype->getName()); ?></td>
            <td><a href="<?php echo $this->url('datatypeEdit', array('id' => $datatype->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translator('Edit')); ?>" />
            </a></td>
            <td><a href="<?php echo $this->url('datatypeDelete', array('id' => $datatype->getId())); ?>">
                <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translator('Delete')); ?>">
            </a></td>
        </tr>
    <?php endforeach; ?>
</table>
