<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Development
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<a href="<?php echo $this->url('development/view/download'); ?>"><?php echo $this->escapeHtml($this->translate('Download all files')); ?></a>
<a href="#" id="upload-link"><?php echo $this->escapeHtml($this->translate('Upload file')); ?></a>

<form class="hide" id="form-content" action="<?php echo $this->url('development/view/upload'); ?>" method="post" enctype="multipart/form-data">
    <p><?php echo $this->escapeHtml($this->translate('Files as: identifier.phtml')); ?></p>
    <input type="file" name="upload[]" multiple="multiple">
    <input type="submit" class="input-submit" value="<?php echo $this->escapeHtml($this->translate('Upload')); ?>">
</form>

<table class="table-list clickable">
    <colgroup>
        <col width="30%">
        <col width="20%">
        <col width="40%">
        <col width="5%">
        <col width="5%">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Identifier')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Description')); ?></th>
            <th class="a-center"><?php echo $this->escapeHtml($this->translate('Edit')); ?></th>
            <th class="a-center"><?php echo $this->escapeHtml($this->translate('Delete')); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->views as $view): ?>
            <tr>
                <td><?php echo $this->escapeHtml($view->getName()); ?></td>
                <td><?php echo $this->escapeHtml($view->getIdentifier()); ?></td>
                <td><?php echo $this->escapeHtml($view->getDescription()); ?></td>
                <td class="a-center">
                    <a href="<?php echo $this->url('development/view/edit', array('id' => $view->getId())); ?>" class="edit-line">
                        <img src="<?php echo $this->cdnBackend('backend/images/icones/edit.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Edit')); ?>" />
                    </a>
                </td>
                <td class="a-center">
                    <a href="<?php echo $this->url('development/view/delete', array('id' => $view->getId())); ?>" class="delete-line">
                        <img src="<?php echo $this->cdnBackend('backend/images/icones/delete.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Delete')); ?>">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
    Gc.initTableList();
    Gc.initUploadLink();
</script>
