<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<table class="table-list">
    <colgroup>
        <col width="30%">
        <col width="20%">
        <col width="40%">
        <col width="5%">
        <col width="5%">
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->escapeHtml($this->translate('Name')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Identifier')); ?></th>
            <th><?php echo $this->escapeHtml($this->translate('Description')); ?></th>
            <th class="a-center"><?php echo $this->escapeHtml($this->translate('Edit')); ?></th>
            <th class="a-center"><?php echo $this->escapeHtml($this->translate('Delete')); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->scripts as $script): ?>
            <tr>
                <td><?php echo $this->escapeHtml($script->getName()); ?></td>
                <td><?php echo $this->escapeHtml($script->getIdentifier()); ?></td>
                <td><?php echo $this->escapeHtml($script->getDescription()); ?></td>
                <td class="a-center">
                    <a href="<?php echo $this->url('scriptEdit', array('id' => $script->getId())); ?>">
                        <img src="<?php echo $this->basePath('images/icones/edit.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Edit')); ?>" />
                    </a>
                </td>
                <td class="a-center">
                    <a href="<?php echo $this->url('scriptDelete', array('id' => $script->getId())); ?>">
                        <img src="<?php echo $this->basePath('images/icones/delete.png'); ?>" alt="<?php echo $this->escapeHtml($this->translate('Delete')); ?>">
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
