<table>
	<tr>
		<th><?php echo $this->escape($this->translate('Id')); ?></th>
		<th><?php echo $this->escape($this->translate('Name')); ?></th>
		<th><?php echo $this->escape($this->translate('Identifier')); ?></th>
		<th><?php echo $this->escape($this->translate('Description')); ?></th>
		<th><?php echo $this->escape($this->translate('Edit')); ?></th>
		<th><?php echo $this->escape($this->translate('Delete')); ?></th>
	</tr>
	<?php foreach($this->layouts as $layout): ?>
		<tr>
			<td><?php echo $layout->getId(); ?></td>
			<td><?php echo $this->escape($layout->getName()); ?></td>
			<td><?php echo $this->escape($layout->getIdentifier()); ?></td>
			<td><?php echo $this->escape($layout->getDescription()); ?></td>
			<td><a href="<?php echo $this->url(array('id' => $layout->getId()), 'layoutEdit'); ?>">
				<img src="<?php echo $this->image('icones/edit.png'); ?>" alt="<?php echo $this->escape($this->translate('Edit')); ?>" />
			</a></td>
			<td><a href="<?php echo $this->url(array('id' => $layout->getId()), 'layoutDelete'); ?>">
				<img src="<?php echo $this->image('icones/delete.png'); ?>" alt="<?php echo $this->escape($this->translate('Delete')); ?>" />
			</a></td>
		</tr>
	<?php endforeach; ?>
</table>

