<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Content
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>
<?php echo $this->form()->openTag($this->form); ?>
    <div class="form-group">
        <?php echo $this->formLabel($this->form->get('source')); ?>
        <?php echo $this->formElement($this->form->get('source')); ?>
    </div>

    <div id="destinations">
        <?php $i = 0; ?>
        <table id="table-trad" class="table clickable table-striped table-hover">
            <colgroup>
                <col class="col-lg-8">
                <col width="col-lg-2">
                <col width="col-lg-2">
            </colgroup>
            <thead>
                <tr>
                    <th><?php echo $this->escapeHtml($this->translate('Destination')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Locale')); ?></th>
                    <th><?php echo $this->escapeHtml($this->translate('Create')); ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <input class="form-control" type="text" name="destination[<?php echo $i; ?>]" size="73">
                    </td>
                    <td>
                        <?php $locales = $this->form->get('locale')->getValueOptions(); ?>
                        <select class="form-control" name="locale[<?php echo $i; ?>]">
                            <?php foreach ($locales as $locale_value => $locale_label): ?>
                                <option value="<?php echo $this->escapeHtml($locale_value); ?>"><?php echo $this->escapeHtml($locale_label); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <span class="btn btn-default add-translate">
                            <i class="glyphicon glyphicon-plus"></i>
                            <?php echo $this->escapeHtml($this->translate('Add')); ?>
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <input type="submit" class="btn btn-warning" id="input-save" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
<?php echo $this->form()->closeTag($this->form); ?>

<script type="text/javascript">
$(document).ready(function(){
    Gc.setOption('locale', $.parseJSON('<?php echo $this->escapeJs($this->json($locales)); ?>'));
    Gc.initTranslator();
    Gc.saveCommand();
    Gc.checkDataChanged();
});
</script>
