<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc
 * @package  Design
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */

 /** @var $this \Zend\View\Renderer\PhpRenderer */

$this->HeadScript()
    ->appendFile('/js/libs/modernizr-2.5.3.min.js', 'text/javascript')
    ->appendFile('/js/libs/jquery-1.7.2.min.js', 'text/javascript')
    ->appendFile('/js/plugins.js', 'text/javascript')
    ->appendFile('/js/libs/jquery-ui-1.8.14.js', 'text/javascript')
    ->appendFile('/js/libs/codemirror/lib/codemirror.js', 'text/javascript')
    ->appendFile('/js/libs/codemirror/mode/xml/xml.js', 'text/javascript')
    ->appendFile('/js/libs/codemirror/mode/javascript/javascript.js', 'text/javascript')
    ->appendFile('/js/libs/codemirror/mode/css/css.js', 'text/javascript')
    ->appendFile('/js/libs/codemirror/mode/clike/clike.js', 'text/javascript')
    ->appendFile('/js/libs/codemirror/mode/php/php.js', 'text/javascript')
    ->appendFile('/js/libs/jquery.jstree.js', 'text/javascript')
    ->appendFile('/js/libs/jquery.contextMenu.js', 'text/javascript')
    ->appendFile('/js/generic-classes.js', 'text/javascript')
    ->appendFile('/js/gotcms.js', 'text/javascript');

$this->HeadLink()
    ->appendStylesheet('/css/style.css')
    ->appendStylesheet('/js/libs/codemirror/lib/codemirror.css')
    ->appendStylesheet('/css/jquery-ui-1.8.14.custom.css')
    ->appendStylesheet('/css/jquery.treeview.css')
    ->appendStylesheet('/css/jquery.contextMenu.css');
?>
<h1>A 404 error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->reason) && $this->reason): ?>

<?php
$reasonMessage= '';
switch ($this->reason) {
    case 'error-controller-cannot-dispatch':
        $reasonMessage = 'The requested controller was unable to dispatch the request.';
        break;
    case 'error-controller-not-found':
        $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
        break;
    case 'error-controller-invalid':
        $reasonMessage = 'The requested controller was not dispatchable.';
        break;
    case 'error-router-no-match':
        $reasonMessage = 'The requested URL could not be matched by routing.';
        break;
    default:
        $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
        break;
}
?>

<p><?php echo $reasonMessage ?></p>

<?php endif ?>

<?php if (isset($this->controller) && $this->controller): ?>

<dl>
    <dt>Controller:</dt>
    <dd><?php $this->escapeHtml($this->controller) ?>
<?php
if (isset($this->controller_class)
    && $this->controller_class
    && $this->controller_class != $this->controller
) {
    echo " (resolves to " . $this->escapeHtml($this->controller_class) . ")";
}
?>
</dd>

<?php endif ?>

<?php if (isset($this->exception) && $this->exception): ?>

<h2>Exception:</h2>

<p><b><?php echo $this->escapeHtml($this->exception->getMessage()) ?></b></p>

<h3>Stack trace</h3>

<pre>
<?php echo $this->exception->getTraceAsString() ?>
</pre>

<?php endif ?>
