<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Config
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */
?>
<h1><?php echo $this->escapeHtml($this->translate('Configure your website')); ?></h1>
<section>
    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Users')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Create, edit, and delete users.')); ?><br>
        </p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Roles')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Limit users access with roles and permissions')); ?><br>
        </p>
    </article>

    <article>
        <h2><?php echo $this->escapeHtml($this->translate('Configuration')); ?></h2>
        <p>
            <?php echo $this->escapeHtml($this->translate('Define the data to be used for the website such as the locale, sessions, name...')); ?><br>
        </p>
    </article>
</section>

