<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category Gc_Tests
 * @package  ZfModules
 * @author   Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license  GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link     http://www.got-cms.com
 */

namespace Content\Controller;

use Gc\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-15 at 23:50:15.
 *
 * @group    ZfModules
 * @category Gc_Tests
 * @package  ZfModules
 */
class MediaControllerTest extends AbstractHttpControllerTestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    public function setUp()
    {
        $this->init();
    }

    /**
     * Test
     *
     * @return void
     */
    public function testIndexAction()
    {
        $this->dispatch('/admin/content/media');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Content');
        $this->assertControllerName('MediaController');
        $this->assertControllerClass('MediaController');
        $this->assertMatchedRouteName('content/media');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testUploadAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * Test
     *
     * @return void
     */
    public function testRemoveActionWithWrongMethod()
    {
        $this->dispatch(
            '/admin/content/media/remove/document/1/property/2/file/',
            'POST',
            array(
            )
        );

        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Content');
        $this->assertControllerName('MediaController');
        $this->assertControllerClass('MediaController');
        $this->assertMatchedRouteName('content/media/remove');
    }

    /**
     * Test
     *
     * @return void
     */
    public function testConnectorAction()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $this->dispatch('/admin/content/media/connector');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Content');
        $this->assertControllerName('MediaController');
        $this->assertControllerClass('MediaController');
        $this->assertMatchedRouteName('content/media/connector');
    }
}
