<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Content
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>

<ul class="nav nav-list">
<?php if ($this->acl('content', 'document')): ?>
    <li class="open">
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-desktop"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Documents')); ?></span>

            <b class="arrow glyphicon glyphicon-tower"></b>
        </a>
        <ul class="submenu">
            <li>
                <?php echo $this->treeview; ?>
            </li>
        </ul>
    </li>
<?php endif; ?>

<?php if ($this->acl('content', 'media')): ?>
    <li>
        <a href="<?php echo $this->url('content/media'); ?>">
            <i class="glyphicon glyphicon-folder-open"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('File manager')); ?></span>
        </a>
    </li>
<?php endif; ?>

<?php if ($this->acl('content', 'translation')): ?>
    <li class="open">
        <a class="menu-toggle" href="#">
            <i class="glyphicon glyphicon-book"></i>
            <span class="menu-text"><?php echo $this->escapeHtml($this->translate('Translations')); ?></span>
            <span class="caret"></span>
        </a>
        <ul class="submenu">
            <li>
                <a href="<?php echo $this->url('content/translation/create'); ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('Create')); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('content/translation'); ?>">
                    <i class="glyphicon glyphicon-arrow-right"></i>
                    <?php echo $this->escapeHtml($this->translate('Edit')); ?>
                </a>
            </li>
        </ul>
    </li>
<?php endif; ?>
</ul>
