<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Module
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
 /** @var $this \Zend\View\Renderer\PhpRenderer */

?>

<?php echo $this->form()->openTag($this->form); ?>
    <?php $element = $this->form->get('module'); ?>
    <div class="form-group">
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formElement($element); ?>

        <?php $modules_info = $element->getAttribute('modules_info'); ?>
        <?php if (!empty($modules_info)): ?>
            <div id="modules">
                <?php foreach ($modules_info as $module_name => $module_info): ?>
                    <div id="<?php echo $this->escapeHtml($this->translate($module_name)); ?>">
                        <?php echo $module_info; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

    <input type="submit" class="btn btn-warning" value="<?php echo $this->escapeHtml($this->translate('Save')); ?>">
<?php echo $this->form()->closeTag($this->form); ?>
<script type="text/javascript">
    Gc.installModule();
</script>
