<?php
/**
 * This source file is part of GotCms.
 *
 * GotCms is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GotCms is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with GotCms. If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 *
 * PHP Version >=5.3
 *
 * @category    Gc
 * @package     Admin
 * @subpackage  Design
 * @author      Pierre Rambaud (GoT) <pierre.rambaud86@gmail.com>
 * @license     GNU/LGPL http://www.gnu.org/licenses/lgpl-3.0.html
 * @link        http://www.got-cms.com
 */
/** @var $this \Zend\View\Renderer\PhpRenderer */

?>

<div class="dashboard<?php if (empty($this->dashboardWelcome)): ?> hide<?php endif; ?>" id="dashboard">
    <a href="#close" class="dashboard-close floatR"><?php echo $this->escapeHtml($this->translate('Close')); ?></a>

    <div class="dashboard-content">
        <h3><?php echo $this->escapeHtml($this->translate('Welcome on your new website GotCms!')); ?></h3>
        <p class="about-description"><?php echo $this->escapeHtml($this->translate('Introduction')); ?></p>
        <div class="dashboard-column-container">

            <p class="dashboard-dismiss">
                <?php echo $this->escapeHtml($this->translate('You know what you do?')); ?>
                <a href="#close" class="dashboard-close"><?php echo $this->escapeHtml($this->translate('Close message.')); ?></a>
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6 widget-column" id="sortable1">
        <div class="widget-box" id="fast-links">
            <div class="widget-header">
                <span><?php echo $this->escapeHtml($this->translate('Fast links')); ?></span>
            </div>
            <div class="widget-body">
                <ul>
                    <li><a href="<?php echo $this->url('content/document/create'); ?>"><?php echo $this->escapeHtml($this->translate('Create document')); ?></a></li>
                    <li><a href="<?php echo $this->url('config/user'); ?>"><?php echo $this->escapeHtml($this->translate('User list')); ?></a></li>
                    <li><a href="<?php echo $this->url('config/general'); ?>"><?php echo $this->escapeHtml($this->translate('General configuration')); ?></a></li>
                    <li><a href="<?php echo $this->url('content/translation/create'); ?>"><?php echo $this->escapeHtml($this->translate('Add translation')); ?></a></li>
                    <li><a href="<?php echo $this->url('content/media'); ?>"><?php echo $this->escapeHtml($this->translate('File manager')); ?></a></li>
                </ul>
            </div>
        </div>

        <?php foreach ($this->customWidgets as $widget): ?>
            <?php if (empty($widget['id']) or empty($widget['title']) or empty($widget['content'])): ?>
                <?php continue; ?>
            <?php endif; ?>
            <div class="widget-box" id="<?php echo $this->escapeHtml(!empty($widget['id']) ? $widget['id'] : ''); ?>">
                <div class="widget-header">
                    <span><?php echo $this->escapeHtml($this->translate(!empty($widget['title']) ? $widget['title'] : '')); ?></span>
                </div>
                <div class="widget-body">
                    <?php echo !empty($widget['content']) ? $widget['content'] : ''; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="col-sm-6 widget-column" id="sortable2">
        <div class="widget-box" id="stats">
            <div class="widget-header">
                <span><?php echo $this->escapeHtml($this->translate('Stats')); ?></span>
            </div>
            <div class="widget-body">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <p class="sub"><?php echo $this->escapeHtml($this->translate('Content')); ?></p>
                        <table class="table table-striped table-bordered">
                            <tbody>
                                <?php foreach ($this->contentStats as $stats): ?>
                                    <tr>
                                        <td class="first">
                                            <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $stats['count']; ?></a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $this->escapeHtml($this->translate($stats['label'])); ?></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-6 col-sm-12">
                        <p class="sub"><?php echo $this->escapeHtml($this->translate('Stats')); ?></p>
                        <table class="table table-striped table-bordered">
                            <tbody>
                                <?php foreach ($this->userStats as $stats): ?>
                                    <tr>
                                        <td class="first">
                                            <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $stats['count']; ?></a>
                                        </td>
                                        <td>
                                            <a href="<?php echo $this->url($stats['route']); ?>"><?php echo $this->escapeHtml($this->translate($stats['label'])); ?></a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="version">
                    <span>
                        <?php echo $this->escapeHtml(sprintf($this->translate('You use GotCms %s'), $this->version)); ?>
                        <?php if (!$this->versionIsLatest): ?>
                            <a class="button" href="<?php echo $this->url('config/cms-update'); ?>"><?php echo $this->escapeHtml(sprintf($this->translate('Update to GotCms %s'), $this->versionLatest)); ?></a>
                        <?php endif; ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    Gc.initDashBoard($.parseJSON('<?php echo $this->escapeJs($this->dashboardSortable); ?>'), '<?php echo $this->escapeJs($this->url('admin/dashboard-save')); ?>');
</script>
